import { posix } from 'node:path';
import type { ProxyContext, ProxyRoute } from '../routes.ts';
import type { FileSpec } from '../file-driver.ts';
import { fileDriver, singleQuote } from '../file-driver.ts';

// Both files this driver owns are generated and replaced wholesale on every
// apply ('owned' mode), the same as the nginx driver's one file. The header
// doubles as each file's ownership mark: an apply only replaces an existing
// file whose first line is exactly this (FileSpec.ownedHeader), since
// proxyConfigPath is shared across drivers and may still name another
// driver's file. HAProxy reads `#` as a comment in both a configuration file
// and a map file, so one header serves both.
const HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';

// The Debian/Ubuntu CA bundle, the same path (and the same single-operator
// platform assumption, research R4) the nginx driver verifies a port-443
// backend against.
const CA_BUNDLE = '/etc/ssl/certs/ca-certificates.crt';

// The operator's own main configuration (the Debian/Ubuntu package default,
// a fixed single-operator assumption -- research R4), validated together
// with the backends file: HAProxy loads the backends file as an extra `-f`
// after it (research R1), and the backends file alone has no frontend and
// no `global`/`defaults`, so `haproxy -c` needs both to check what the
// running proxy will actually load -- including the frontend's map lookup.
const MAIN_CONFIG = '/etc/haproxy/haproxy.cfg';

// The map file's path: `bellhop.map` in configPath's own directory (research
// R9). The operator's frontend names this path in its `use_backend ... map()`
// lookup, so it is derived rather than configured -- one setting
// (proxyConfigPath) moves both files together. POSIX because the path is on
// the proxy host, never this machine.
export function mapPath(configPath: string): string {
  return posix.join(posix.dirname(configPath), 'bellhop.map');
}

// Characters HAProxy accepts in a backend name (research R2, checked with a
// real `haproxy -c`: a `/` or a space fails it); anything else becomes `_`.
const UNSAFE_NAME_CHARS = /[^A-Za-z0-9_.:-]/g;

// One backend name per route, in route order (research R3):
// `bellhop_<owner.type>_<sanitised name>`. The owner type keeps a host and a
// guest that share a name apart, and the `bellhop_` prefix keeps these clear
// of the operator's own backends. Two names that sanitise alike (`a b`,
// `a/b`) would otherwise collide, so a name already taken by an earlier
// route gets `_2`, `_3`, ... -- the first suffix no earlier route holds, so
// a suffixed name can never land on a route literally named `a_b_2`. This is
// the join key between the map file's second column and the backends file's
// `backend` lines, which is why both files are rendered from this one list.
export function backendNames(routes: ProxyRoute[]): string[] {
  const taken = new Set<string>();
  return routes.map((route) => {
    const base = `bellhop_${route.owner.type}_${route.owner.name.replace(UNSAFE_NAME_CHARS, '_')}`;
    let name = base;
    for (let n = 2; taken.has(name); n++) {
      name = `${base}_${n}`;
    }
    taken.add(name);
    return name;
  });
}

// The server line's TLS suffix (research R6) -- the same rule the Caddy and
// nginx drivers apply: TLS without verification when the entry says its
// backend certificate can't be verified, verified TLS for a port-443
// backend, plain HTTP otherwise. `verify required` is spelled out because
// HAProxy's default depends on the operator's own `global` section.
function tlsSuffix(backend: ProxyRoute['backend']): string {
  if (backend.insecureTls) return ' ssl verify none';
  if (backend.port === 443) return ` ssl verify required ca-file ${CA_BUNDLE}`;
  return '';
}

// One backend block (contract "Backend block", research R5) -- each line
// matches what the Caddy and nginx drivers give a backend:
//  - `mode http`: HTTP-level handling, needed for the header rewrites below
//    and for the frontend's Host-based map lookup.
//  - `timeout server`/`timeout tunnel 1d`: the nginx driver's 1d
//    read/send timeouts, so a quiet WebSocket or server-sent-events stream
//    isn't cut off by the operator's `defaults` timeouts. HAProxy passes
//    WebSocket upgrades natively in HTTP mode and neither buffers nor limits
//    request bodies by default, so nothing else is needed for parity.
//  - X-Forwarded-For is *set* to the client address, never appended to --
//    the nginx driver's anti-spoofing choice, so a client can't pose as a
//    LAN address.
//  - X-Forwarded-Proto is the literal `https`: every request reaching a
//    Bellhop backend came through the operator's TLS frontend (research R1).
//  - X-Forwarded-Host is the original Host; Host itself passes through
//    unchanged (HAProxy's default), as with Caddy and nginx.
//  - X-Forwarded-Port is ctx.externalPort, like every driver (issue #91).
//  - No health `check` on the server line: a single-server backend gains
//    nothing from one, and a failing check would turn a slow backend into
//    a 503.
function renderBackend(route: ProxyRoute, name: string, ctx: ProxyContext): string[] {
  return [
    `backend ${name}`,
    '    mode http',
    '    timeout server 1d',
    '    timeout tunnel 1d',
    '    http-request set-header X-Forwarded-For %[src]',
    '    http-request set-header X-Forwarded-Proto https',
    '    http-request set-header X-Forwarded-Host %[req.hdr(host)]',
    `    http-request set-header X-Forwarded-Port ${ctx.externalPort}`,
    `    server app ${route.backend.ip}:${route.backend.port}${tlsSuffix(route.backend)}`,
  ];
}

// Renders every route into the two files this driver owns (contract
// "Backends file"/"Map file"): the backends file at configPath -- the header,
// then each backend block preceded by a blank line -- and the map file
// beside it -- the header, then one `<hostname> <backend>` line per route
// hostname, canonical first, lower-cased because the operator's frontend
// lower-cases the Host header before the lookup. Both are just the header
// with zero routes. Routes are in buildRoutes order, the same convention
// every driver follows.
//
// An `oidc` route renders exactly like an ungated one -- the app checks the
// login itself -- and unauthenticatedPaths never appear, since they only
// mean something on a forward-gated route. A `forward` route throws: HAProxy
// has no forward-auth this driver can emit, and checkCapabilities (which
// runSyncProxy runs first) already refuses one with the standard message, so
// this is only a backstop against a caller that skipped that check ever
// deploying a forward-gated route ungated.
export function render(routes: ProxyRoute[], ctx: ProxyContext, configPath: string): FileSpec[] {
  const map = mapPath(configPath);
  if (map === configPath) {
    throw new Error(
      `proxyConfigPath '${configPath}' is where the HAProxy driver writes its map file (bellhop.map beside the backends file) -- ` +
        `point proxyConfigPath at a different file (bellhop set-config proxyConfigPath <path> --apply)`
    );
  }
  for (const route of routes) {
    if (route.auth.mode === 'forward') {
      throw new Error(`HAProxy cannot enforce forward-auth for entry '${route.owner.name}'`);
    }
  }

  const names = backendNames(routes);
  const backendLines: string[] = [HEADER];
  const mapLines: string[] = [HEADER];
  routes.forEach((route, i) => {
    backendLines.push('', ...renderBackend(route, names[i], ctx));
    for (const hostname of route.hostnames) {
      mapLines.push(`${hostname.toLowerCase()} ${names[i]}`);
    }
  });

  // Backends first, then the map: fileDriver's plan() previews them in this
  // order, and its apply script backs up, writes and restores them together.
  return [
    { path: configPath, content: backendLines.join('\n'), mode: 'owned', ownedHeader: HEADER },
    { path: map, content: mapLines.join('\n'), mode: 'owned', ownedHeader: HEADER },
  ];
}

export const haproxyDriver = fileDriver({
  id: 'haproxy',
  label: 'HAProxy',
  // OIDC only: HAProxy has no forward-auth Bellhop renders, so a
  // forward-gated entry is refused by checkCapabilities with the standard
  // message before render() ever sees it (research R8). HAProxy cannot
  // obtain certificates either -- the operator's frontend serves its own
  // (research R7) -- so there is no ACME DNS-01 record for
  // prune-acme-challenges to clean up after.
  capabilities: { authModes: ['oidc'], acmeDns01ViaCloudflare: false },
  defaultConfigPath: '/etc/haproxy/bellhop.cfg',
  // No document root of its own to serve a status page from (research R7).
  statusPage: null,
  configPathNote:
    "HAProxy replaces this whole file and writes bellhop.map beside it on every apply, and refuses to replace a file it didn't generate.",
  render,
  validateCommand: (configPath) => `haproxy -c -f ${MAIN_CONFIG} -f ${singleQuote(configPath)}`,
  reloadCommand: 'systemctl reload haproxy',
  // Both files, so the status page and a snapshot read back everything this
  // driver deployed -- derived from configPath alone, never from render, so
  // a read-only snapshot still works when the inventory itself is invalid.
  configFiles: (configPath) => [configPath, mapPath(configPath)],
});
