import type { ProxyContext, ProxyRoute } from '../routes.ts';
import type { FileSpec } from '../file-driver.ts';
import { fileDriver } from '../file-driver.ts';
import { quote, renderServerBody, type ServerBodyVars } from '../nginx-locations.ts';

// The whole file is generated and replaced wholesale on every apply
// ('owned' mode, research R8) -- unlike the Caddy driver, nginx has no
// admin API and no other file this toolkit's operator hand-authors
// alongside a managed section, so there is nothing to preserve. The header
// doubles as the file's ownership mark: an apply only replaces an existing
// file whose first line is exactly this (FileSpec.ownedHeader).
const HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';

// Two `map` blocks emitted unconditionally, even with zero routes, so the
// file's shape never depends on the inventory (research R8):
//  - $bellhop_connection_upgrade turns a WebSocket Upgrade request's
//    Connection header into "upgrade" and every other request's into "",
//    matching Caddy's own automatic WebSocket passthrough (research R4).
//  - $bellhop_http_host is the Authentik nginx recipe's $ak_http_host map
//    under a bellhop-prefixed name (research R3): $http_host, falling back
//    to $host, so an explicit port in the original Host header survives.
// Bellhop-prefixed rather than the recipe's own names because map/variable
// names are global across the whole nginx configuration, and an operator's
// other files may already define the recipe's own names -- defining a map
// twice fails `nginx -t` (research R3). These two variables only make sense
// at http {} level (where a map block lives), which is exactly why the
// shared src/lib/proxy/nginx-locations.ts renderer takes them as a
// parameter rather than hardcoding them -- the Nginx Proxy Manager driver
// (issue #31), whose advanced_config lands inside server {}, cannot define
// a map of its own and uses nginx's own $http_host/$http_connection
// instead.
const MAP_BLOCKS = [
  'map $http_upgrade $bellhop_connection_upgrade {',
  '    default upgrade;',
  "    ''      '';",
  '}',
  '',
  'map $http_host $bellhop_http_host {',
  '    default $http_host;',
  "    ''      $host;",
  '}',
].join('\n');

// The nginx driver's own map-block variables (see MAP_BLOCKS above) --
// passed to the shared renderServerBody so its output references these
// instead of nginx's built-in $http_host/$http_connection.
const NGINX_VARS: ServerBodyVars = { host: '$bellhop_http_host', connection: '$bellhop_connection_upgrade' };

// One server block per route (contract "Ungated or OIDC route" /
// "Forward-gated route"): the listen/server_name/TLS-certificate lines this
// driver owns, followed by the shared body src/lib/proxy/nginx-locations.ts's
// renderServerBody produces for every nginx-config-emitting driver alike
// (issue #31, FR-016) -- client_max_body_size through the last location,
// with this driver's own $bellhop_http_host/$bellhop_connection_upgrade
// variables (NGINX_VARS above).
function renderServerBlock(route: ProxyRoute, ctx: ProxyContext): string[] {
  return [
    'server {',
    '    listen 443 ssl;',
    '    listen [::]:443 ssl;',
    `    server_name ${route.hostnames.join(' ')};`,
    '',
    `    ssl_certificate ${quote(ctx.tls.certificatePath)};`,
    `    ssl_certificate_key ${quote(ctx.tls.keyPath)};`,
    '',
    ...renderServerBody(route, ctx, NGINX_VARS),
    '}',
  ];
}

// Renders every route into the one file this driver owns whole: the header
// comment, both map blocks (always present, research R8), then one server
// block per route in buildRoutes order, each preceded by a blank line.
// Reads the proxy-neutral ProxyRoute[]/ProxyContext shapes buildRoutes/
// buildProxyContext have already derived, the same convention the Caddy
// driver follows.
export function render(routes: ProxyRoute[], ctx: ProxyContext, configPath: string): FileSpec[] {
  const lines: string[] = [HEADER, '', MAP_BLOCKS];
  for (const route of routes) {
    lines.push('', ...renderServerBlock(route, ctx));
  }
  // ownedHeader: an apply refuses to replace an existing file that doesn't
  // start with this line (see buildFileDriverScript), since proxyConfigPath
  // is shared across drivers and may still point at another driver's file.
  return [{ path: configPath, content: lines.join('\n'), mode: 'owned', ownedHeader: HEADER }];
}

export const nginxDriver = fileDriver({
  id: 'nginx',
  label: 'nginx',
  // nginx cannot obtain its own certificates the way Caddy does (research
  // R1), so it has no ACME DNS-01-via-Cloudflare capability of its own --
  // the shared certificate every server block references (ctx.tls) is
  // provisioned by the operator (certbot or similar) outside this toolkit.
  // Always false, unaffected by any inventory setting -- the function
  // wrapper here exists only to satisfy the updated DriverCapabilities
  // type (issue #51).
  capabilities: { authModes: ['forward', 'oidc'], acmeDns01ViaCloudflare: () => false, tlsSources: ['files'], defaultTlsSource: 'files' },
  defaultConfigPath: '/etc/nginx/conf.d/bellhop.conf',
  // The Debian/Ubuntu nginx package's default document root -- the same
  // platform this driver already assumes for its upstream CA bundle path --
  // and the placeholder the Settings page shows. Serving it is the
  // operator's own hand-authored server block's job, the same way Caddy's
  // status page block is hand-authored.
  statusPage: { suggestedPath: '/var/www/html/index.html' },
  usesSharedCertificate: true,
  configPathNote: "nginx replaces this whole file on every apply, and refuses to replace a file it didn't generate.",
  render,
  validateCommand: () => 'nginx -t',
  reloadCommand: 'systemctl reload nginx',
});
