import type { ProxyContext, ProxyRoute } from '../routes.ts';
import type { FileSpec } from '../file-driver.ts';
import { fileDriver } from '../file-driver.ts';

// The whole file is generated and replaced wholesale on every apply
// ('owned' mode, research R8) -- unlike the Caddy driver, nginx has no
// admin API and no other file this toolkit's operator hand-authors
// alongside a managed section, so there is nothing to preserve.
const HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';

// Two `map` blocks emitted unconditionally, even with zero routes, so the
// file's shape never depends on the inventory (research R8):
//  - $bellhop_connection_upgrade turns a WebSocket Upgrade request's
//    Connection header into "upgrade" and every other request's into "",
//    matching Caddy's own automatic WebSocket passthrough (research R4).
//  - $bellhop_http_host is the Authentik nginx recipe's $ak_http_host map
//    under a bellhop-prefixed name (research R3): $http_host, falling back
//    to $host, so an explicit port in the original Host header survives.
// Bellhop-prefixed rather than the recipe's own names because map/variable
// names are global across the whole nginx configuration, and an operator's
// other files may already define the recipe's own names -- defining a map
// twice fails `nginx -t` (research R3).
const MAP_BLOCKS = [
  'map $http_upgrade $bellhop_connection_upgrade {',
  '    default upgrade;',
  "    ''      '';",
  '}',
  '',
  'map $http_host $bellhop_http_host {',
  '    default $http_host;',
  "    ''      $host;",
  '}',
].join('\n');

// nginx double-quoted string: backslash-escape `\` then `"` (order matters,
// so an existing backslash from the first pass is never re-escaped by the
// second). Used for certificate paths here; User Story 2 reuses this for
// exempt-path locations.
export function quote(value: string): string {
  return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

// The lines shared by `location /` and (User Story 2) every exempt
// location, for one backend (contract "Proxy lines", research R4/R5).
// Parity with Caddy's reverse_proxy defaults: nginx's own defaults are the
// opposite of Caddy's on every one of these points (Host becomes the
// upstream address, no forwarded headers, no WebSocket upgrade, a 1 MB body
// limit -- capped at the server level instead, see below -- and buffered
// responses), so backends that work behind the Caddy driver today would
// otherwise break on switching drivers.
function proxyLines(backend: ProxyRoute['backend'], ctx: ProxyContext): string[] {
  // Caddy's own rule (research R5): TLS to the upstream when insecureTls is
  // set, or the backend port is 443 -- otherwise plain http.
  const https = backend.insecureTls || backend.port === 443;
  const scheme = https ? 'https' : 'http';
  const lines = [
    `        proxy_pass ${scheme}://${backend.ip}:${backend.port};`,
    '        proxy_http_version 1.1;',
    '        proxy_set_header Host $bellhop_http_host;',
    '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
    '        proxy_set_header X-Forwarded-Proto $scheme;',
    '        proxy_set_header X-Forwarded-Host $bellhop_http_host;',
    `        proxy_set_header X-Forwarded-Port ${ctx.externalPort};`,
    '        proxy_set_header Upgrade $http_upgrade;',
    '        proxy_set_header Connection $bellhop_connection_upgrade;',
  ];
  if (https) {
    if (backend.insecureTls) {
      lines.push('        proxy_ssl_verify off;');
    } else {
      // A port-443 backend without insecureTls: nginx never verifies an
      // upstream certificate unless told to, so without this a plain
      // port-443 proxy_pass would silently lose the verification Caddy
      // performs automatically (research R5). The CA bundle path is the
      // Debian/Ubuntu one, the same platform assumption as this driver's
      // own conf.d default path.
      lines.push('        proxy_ssl_verify on;');
      lines.push('        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;');
    }
  }
  return lines;
}

// One server block for an ungated or OIDC-mode route (contract "Ungated or
// OIDC route"). A forward-gated route renders identically here in User
// Story 1 -- User Story 2 adds the Authentik forward-auth lines/locations
// for route.auth.mode === 'forward', following research R3/R7.
function renderServerBlock(route: ProxyRoute, ctx: ProxyContext): string[] {
  return [
    'server {',
    '    listen 443 ssl;',
    '    listen [::]:443 ssl;',
    `    server_name ${route.hostnames.join(' ')};`,
    '',
    `    ssl_certificate ${quote(ctx.tls.certificatePath)};`,
    `    ssl_certificate_key ${quote(ctx.tls.keyPath)};`,
    '',
    '    client_max_body_size 0;',
    '    proxy_buffering off;',
    '',
    '    location / {',
    ...proxyLines(route.backend, ctx),
    '    }',
    '}',
  ];
}

// Renders every route into the one file this driver owns whole: the header
// comment, both map blocks (always present, research R8), then one server
// block per route in buildRoutes order, each preceded by a blank line.
// Reads the proxy-neutral ProxyRoute[]/ProxyContext shapes buildRoutes/
// buildProxyContext have already derived, the same convention the Caddy
// driver follows.
export function render(routes: ProxyRoute[], ctx: ProxyContext, configPath: string): FileSpec[] {
  const lines: string[] = [HEADER, '', MAP_BLOCKS];
  for (const route of routes) {
    lines.push('', ...renderServerBlock(route, ctx));
  }
  return [{ path: configPath, content: lines.join('\n'), mode: 'owned' }];
}

export const nginxDriver = fileDriver({
  id: 'nginx',
  // nginx cannot obtain its own certificates the way Caddy does (research
  // R1), so it has no ACME DNS-01-via-Cloudflare capability of its own --
  // the shared certificate every server block references (ctx.tls) is
  // provisioned by the operator (certbot or similar) outside this toolkit.
  capabilities: { authModes: ['forward', 'oidc'], acmeDns01ViaCloudflare: false },
  defaultConfigPath: '/etc/nginx/conf.d/bellhop.conf',
  render,
  validateCommand: () => 'nginx -t',
  reloadCommand: 'systemctl reload nginx',
});
