import { createHash } from 'node:crypto';
import { parse, stringify, Scalar } from 'yaml';
import type { ProxyContext, ProxyRoute } from '../routes.ts';
import type { FileSpec } from '../file-driver.ts';
import { fileDriver } from '../file-driver.ts';

// The whole file is generated and replaced wholesale on every apply ('owned'
// mode), the same convention as the nginx/HAProxy drivers -- Traefik's file
// provider has no admin API of its own to reconcile against, and nothing
// this toolkit's operator hand-authors belongs inside a Bellhop-managed
// section of it (research.md R1). The header doubles as the file's
// ownership mark (FileSpec.ownedHeader): an apply only replaces an existing
// file whose first line is exactly this.
const HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';

// research.md R5: this file is written atomically (a same-directory temp
// file, then `mv -f`) rather than truncated in place with `cat >`, because
// Traefik's file-provider watcher reads the directory live -- an in-place
// truncate would briefly expose a half-written or empty file to it. Caddy
// and nginx never set this: both reload explicitly only after a successful
// validate, so a partial file is never read by either.
const ATOMIC = true;

// research.md R7: every object name is prefixed `bellhop-`, and a route's
// own objects are derived from its canonical hostname (hostnames[0]) by this
// injective encoding -- lowercase, then every `-` doubled, then every `.`
// turned into a single `-`. Doubling `-` first is what keeps the encoding
// injective: a hostname's own hyphens are distinguishable from the hyphens
// this encoding introduces for `.`, so two different hostnames can never
// collide on the same encoded name (e.g. 'a.b-c.example.com' and
// 'a-b.c.example.com' encode differently -- see the test for this).
export function encodeHostname(hostname: string): string {
  return hostname.toLowerCase().replace(/-/g, '--').replace(/\./g, '-');
}

export function routeName(canonicalHostname: string): string {
  return `bellhop-route-${encodeHostname(canonicalHostname)}`;
}

export function exemptName(canonicalHostname: string): string {
  return `bellhop-exempt-${encodeHostname(canonicalHostname)}`;
}

export function outpostName(canonicalHostname: string): string {
  return `bellhop-outpost-${encodeHostname(canonicalHostname)}`;
}

// research.md R6: a rule's Go-string-literal value is backtick-quoted unless
// it contains a backtick itself, in which case it's written as a
// double-quoted Go string instead -- JSON's escaping rules (backslash and
// double-quote escaped, everything else passed through) happen to match
// Go's own double-quoted string syntax closely enough that JSON.stringify
// produces a value Traefik parses correctly (live-verified: a rule
// containing `Path("/a\`b\"c\\d")` parsed and the router stayed enabled).
// Hostnames never contain a backtick in practice, so they always take the
// backtick branch, but this one function is used for both so there is only
// one place this rule lives.
export function ruleValue(value: string): string {
  return value.includes('`') ? JSON.stringify(value) : `\`${value}\``;
}

// The shared middleware every router carries (research.md R7/R9, issue
// #91's X-Forwarded-Port convention every driver follows): a `headers`
// middleware that sets X-Forwarded-Port to the fixed external port, so a
// backend building absolute external URLs sees the real one. Always present,
// even with zero routes (research.md R7) -- ctx.externalPort is a plain
// number turned into a string here since Traefik's customRequestHeaders
// values are header text, not YAML-typed data; the `yaml` package quotes a
// numeric-looking string like "443" automatically so it round-trips as a
// string rather than an integer.
function forwardedPortMiddleware(ctx: ProxyContext): unknown {
  return { headers: { customRequestHeaders: { 'X-Forwarded-Port': String(ctx.externalPort) } } };
}

// The generation-marker middleware (research.md R3): an unused `headers`
// middleware whose sole purpose is to prove, via a 200 from Traefik's own
// read-only API, that a *specific* rendered version of this file has been
// loaded -- Traefik's file-provider watcher is throttled, so "the routers
// are healthy" can't be checked the instant the write finishes without some
// way to tell the old version's routers from the new one's. The value is a
// YAML string, not a bare scalar: a hash that happens to be all-digits (hex
// still only overlaps decimal on 0-9) would otherwise be read back as a
// number, so the value is an explicit Scalar with QUOTE_DOUBLE forced --
// `yaml`'s own stringify already quotes a plain string that merely looks
// numeric (see forwardedPortMiddleware above), but a Scalar is used here
// too so the marker's own round-trip-as-a-string property doesn't
// accidentally depend on that best-effort heuristic.
function generationMarkerMiddleware(hash: string): unknown {
  const value = new Scalar(hash);
  value.type = 'QUOTE_DOUBLE';
  return { headers: { customRequestHeaders: { 'X-Bellhop-Generation': value } } };
}

// research.md R8: the backend URL scheme follows the same rule the Caddy and
// nginx drivers already apply -- https when the entry says its own
// certificate can't be verified, or when the backend port is the standard
// HTTPS one (443), plain http otherwise. With insecureTls the service names
// the shared bellhop-insecure-backend-tls transport (insecureSkipVerify);
// without it, Traefik's default transport verifies the certificate against
// the system CA pool for a 443 backend, matching Caddy's own behavior.
function backendUrl(backend: ProxyRoute['backend']): string {
  const scheme = backend.insecureTls || backend.port === 443 ? 'https' : 'http';
  return `${scheme}://${backend.ip}:${backend.port}`;
}

// One route's main router + service (contract "Rendered file: example", the
// *wiki* entry's shape) -- forward-auth/outpost/exempt objects are User
// Story 2 and are not produced here at all yet; every route, gated or not,
// gets exactly this router+service pair for now.
function renderRouteObjects(
  route: ProxyRoute,
  ctx: ProxyContext,
  routers: Record<string, unknown>,
  services: Record<string, unknown>
): { usesInsecureTls: boolean } {
  const canonical = route.hostnames[0];
  const name = routeName(canonical);

  routers[name] = {
    rule: route.hostnames.map((hostname) => `Host(${ruleValue(hostname)})`).join(' || '),
    entryPoints: ['websecure'],
    service: name,
    middlewares: ['bellhop-forwarded-port'],
    tls: { certResolver: ctx.certResolver },
  };

  const loadBalancer: Record<string, unknown> = { servers: [{ url: backendUrl(route.backend) }] };
  if (route.backend.insecureTls) {
    loadBalancer.serversTransport = 'bellhop-insecure-backend-tls';
  }
  services[name] = { loadBalancer };

  return { usesInsecureTls: route.backend.insecureTls };
}

// Renders every route into the one file this driver owns whole (contract
// "Rendered file: example"): the header comment, then a `http:` document
// built from the proxy-neutral ProxyRoute[]/ProxyContext buildRoutes/
// buildProxyContext have already derived, the same convention every other
// driver follows. `routers`/`services` are omitted entirely when empty
// (data-model.md), but `middlewares` always exists -- bellhop-forwarded-port
// plus the generation marker, so the file is never actually empty even with
// zero routes (research.md R7, live-checked: a file with only middlewares
// loads fine).
//
// The marker's hash is the SHA-256 of the file rendered *without* the
// marker (research.md R3), so it is computed in two passes: build and
// stringify the document with every other object in place first, hash that
// text, then add the marker middleware (named after the hash) and stringify
// again for the real output. This is what makes the hash change whenever
// anything else about the file changes, and stay stable otherwise.
export function render(routes: ProxyRoute[], ctx: ProxyContext, configPath: string): FileSpec[] {
  const routers: Record<string, unknown> = {};
  const services: Record<string, unknown> = {};
  const middlewares: Record<string, unknown> = { 'bellhop-forwarded-port': forwardedPortMiddleware(ctx) };
  let anyInsecureTls = false;

  for (const route of routes) {
    const { usesInsecureTls } = renderRouteObjects(route, ctx, routers, services);
    anyInsecureTls = anyInsecureTls || usesInsecureTls;
  }

  const serversTransports: Record<string, unknown> = anyInsecureTls
    ? { 'bellhop-insecure-backend-tls': { insecureSkipVerify: true } }
    : {};

  function buildHttp(withMarker: Record<string, unknown> | null): Record<string, unknown> {
    const http: Record<string, unknown> = {};
    if (Object.keys(routers).length > 0) http.routers = routers;
    if (Object.keys(services).length > 0) http.services = services;
    http.middlewares = withMarker ? { ...middlewares, ...withMarker } : middlewares;
    if (Object.keys(serversTransports).length > 0) http.serversTransports = serversTransports;
    return http;
  }

  const contentWithoutMarker = `${HEADER}\n${stringify({ http: buildHttp(null) })}`;
  const hash = createHash('sha256').update(contentWithoutMarker).digest('hex').slice(0, 12);
  const markerName = `bellhop-generation-${hash}`;
  const content = `${HEADER}\n${stringify({ http: buildHttp({ [markerName]: generationMarkerMiddleware(hash) }) })}`;

  return [{ path: configPath, content, mode: 'owned', ownedHeader: HEADER, atomic: ATOMIC }];
}

// Parses a rendered file back into the router/middleware names User Story 3's
// API validate step needs -- both read `http.routers`/`http.middlewares`
// with `parse` (the same `yaml` package `render` writes with) rather than
// re-deriving names from ProxyRoute[], so the validate step always checks
// exactly what the file on disk actually contains, not what a caller thinks
// it should contain.

// The one middleware among http.middlewares whose name starts with the
// generation-marker prefix -- exactly one is ever rendered (see render()
// above), so a file this driver produced always has one.
export function generationMarkerName(content: string): string {
  const doc = parse(content) as { http?: { middlewares?: Record<string, unknown> } } | null;
  const names = Object.keys(doc?.http?.middlewares ?? {});
  const marker = names.find((name) => name.startsWith('bellhop-generation-'));
  if (marker === undefined) {
    throw new Error('Rendered Traefik configuration has no generation-marker middleware');
  }
  return marker;
}

// Every router name, in the order render() wrote them (an object's own key
// order is preserved by both `stringify` and `parse`).
export function routerNames(content: string): string[] {
  const doc = parse(content) as { http?: { routers?: Record<string, unknown> } } | null;
  return Object.keys(doc?.http?.routers ?? {});
}

export const traefikDriver = fileDriver({
  id: 'traefik',
  label: 'Traefik',
  // Traefik's forward-auth and OIDC both work the same way every other
  // driver's do -- see User Story 2 for the forward-auth objects, not yet
  // rendered by this file. acmeDns01ViaCloudflare mirrors Caddy's: Traefik's
  // own certificate resolver (ctx.certResolver) can be configured for
  // Cloudflare DNS-01 in the operator's own static configuration, which is
  // what prune-acme-challenges exists to clean up stray records from.
  capabilities: { authModes: ['forward', 'oidc'], acmeDns01ViaCloudflare: true },
  defaultConfigPath: '/etc/traefik/dynamic/bellhop.yml',
  // Traefik has no static-file server of its own (research.md R11) -- an
  // operator who wants a status page serves it elsewhere.
  statusPage: null,
  usesCertResolver: true,
  usesApiUrl: true,
  configPathNote:
    "Traefik's file provider must watch this file's directory. The whole file is replaced on every apply, and a file Bellhop didn't generate is refused.",
  render,
  // User Story 3 wires the real API check (research.md R2/R4); until then
  // there is nothing to validate, so the apply script writes and lets
  // Traefik's own watcher pick the file up with no check in between.
  validateCommand: () => null,
  validateLabel: 'Traefik API check',
  // Traefik's file-provider watcher reloads on its own once the write
  // lands -- there is no reload command to run.
  reloadCommand: null,
});
