import { createHash } from 'node:crypto';
import { parse, stringify, Scalar } from 'yaml';
import type { PathPattern, ProxyContext, ProxyRoute } from '../routes.ts';
import type { FileSpec } from '../file-driver.ts';
import { fileDriver, singleQuote } from '../file-driver.ts';
import { settingFix } from '../../settings-hint.ts';
// Shared with the nginx driver (issue #31/#35): the same root-prefix/dedupe/
// outpost-namespace rules a forward-gated route's exempt patterns must obey
// no matter which driver renders them -- see nginx-locations.ts's own
// comments on each for the reasoning; reused here rather than duplicated.
import { candidateExemptPatterns, isRootPrefix } from '../nginx-locations.ts';

// The whole file is generated and replaced wholesale on every apply ('owned'
// mode), the same convention as the nginx/HAProxy drivers -- Traefik's file
// provider has no admin API of its own to reconcile against, and nothing
// this toolkit's operator hand-authors belongs inside a Bellhop-managed
// section of it (research.md R1). The header doubles as the file's
// ownership mark (FileSpec.ownedHeader): an apply only replaces an existing
// file whose first line is exactly this.
const HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';

// research.md R5: this file is written atomically (a same-directory temp
// file, then `mv -f`) rather than truncated in place with `cat >`, because
// Traefik's file-provider watcher reads the directory live -- an in-place
// truncate would briefly expose a half-written or empty file to it. Caddy
// and nginx never set this: both reload explicitly only after a successful
// validate, so a partial file is never read by either.
const ATOMIC = true;

// research.md R7: every object name is prefixed `bellhop-`, and a route's
// own objects are derived from its canonical hostname (hostnames[0]) by this
// encoding -- lowercase, then every `-` doubled, then every `.` turned into
// a single `-`. Doubling `-` first keeps a hostname's own hyphens
// distinguishable from the ones this encoding introduces for `.` (e.g.
// 'a.b-c.example.com' and 'a-b.c.example.com' encode differently -- see the
// test for this). It is injective for valid DNS hostnames, whose labels
// never start or end with '-'; a subdomain is a plain string in the schema,
// though, so 'a-.b' and 'a.-b' can still collide -- render() rejects a
// collision rather than letting one route's objects overwrite another's.
export function encodeHostname(hostname: string): string {
  return hostname.toLowerCase().replace(/-/g, '--').replace(/\./g, '-');
}

export function routeName(canonicalHostname: string): string {
  return `bellhop-route-${encodeHostname(canonicalHostname)}`;
}

export function exemptName(canonicalHostname: string): string {
  return `bellhop-exempt-${encodeHostname(canonicalHostname)}`;
}

export function outpostName(canonicalHostname: string): string {
  return `bellhop-outpost-${encodeHostname(canonicalHostname)}`;
}

// research.md R6: a rule's Go-string-literal value is backtick-quoted unless
// it contains a backtick itself, in which case it's written as a
// double-quoted Go string instead -- JSON's escaping rules (backslash and
// double-quote escaped, everything else passed through) happen to match
// Go's own double-quoted string syntax closely enough that JSON.stringify
// produces a value Traefik parses correctly (live-verified: a rule
// containing `Path("/a\`b\"c\\d")` parsed and the router stayed enabled).
// Hostnames never contain a backtick in practice, so they always take the
// backtick branch, but this one function is used for both so there is only
// one place this rule lives.
export function ruleValue(value: string): string {
  return value.includes('`') ? JSON.stringify(value) : `\`${value}\``;
}

// The shared middleware every router carries (research.md R7/R9, issue
// #91's X-Forwarded-Port convention every driver follows): a `headers`
// middleware that sets X-Forwarded-Port to the fixed external port, so a
// backend building absolute external URLs sees the real one. Always present,
// even with zero routes (research.md R7) -- ctx.externalPort is a plain
// number turned into a string here since Traefik's customRequestHeaders
// values are header text, not YAML-typed data; the `yaml` package quotes a
// numeric-looking string like "443" automatically so it round-trips as a
// string rather than an integer.
function forwardedPortMiddleware(ctx: ProxyContext): unknown {
  return { headers: { customRequestHeaders: { 'X-Forwarded-Port': String(ctx.externalPort) } } };
}

// The five identity headers Authentik's forward-auth hands a backend -- the
// same five (no entitlements) every other driver forwards.
const AUTHENTIK_IDENTITY_HEADERS = [
  'X-authentik-username',
  'X-authentik-groups',
  'X-authentik-email',
  'X-authentik-name',
  'X-authentik-uid',
];

// The shared header-strip middleware every router lists first (research.md
// R9): Traefik removes a request header whose customRequestHeaders value is
// the empty string, so a client-sent X-authentik-* header never reaches a
// backend that trusts it -- the HAProxy driver's `del-header x-authentik-`
// for the same reason. Without it, any router with no forward-auth in front
// (an exempt path on a gated app, an ungated or OIDC app, Bellhop's own web
// UI) would pass a spoofed identity straight through. On a forward-gated
// router it runs before bellhop-authentik, whose authResponseHeaders then
// set the real values from Authentik's answer. Each value is an explicit
// double-quoted Scalar so it can never render as a YAML null.
function stripAuthentikHeadersMiddleware(): unknown {
  const headers: Record<string, Scalar> = {};
  for (const name of AUTHENTIK_IDENTITY_HEADERS) {
    const empty = new Scalar('');
    empty.type = 'QUOTE_DOUBLE';
    headers[name] = empty;
  }
  return { headers: { customRequestHeaders: headers } };
}

// Every Bellhop router's middleware list starts with these two, in this order.
const BASE_MIDDLEWARES = ['bellhop-strip-authentik-headers', 'bellhop-forwarded-port'];

// The generation-marker middleware (research.md R3): an unused `headers`
// middleware whose sole purpose is to prove, via a 200 from Traefik's own
// read-only API, that a *specific* rendered version of this file has been
// loaded -- Traefik's file-provider watcher is throttled, so "the routers
// are healthy" can't be checked the instant the write finishes without some
// way to tell the old version's routers from the new one's. The value is a
// YAML string, not a bare scalar: a hash that happens to be all-digits (hex
// still only overlaps decimal on 0-9) would otherwise be read back as a
// number, so the value is an explicit Scalar with QUOTE_DOUBLE forced --
// `yaml`'s own stringify already quotes a plain string that merely looks
// numeric (see forwardedPortMiddleware above), but a Scalar is used here
// too so the marker's own round-trip-as-a-string property doesn't
// accidentally depend on that best-effort heuristic.
function generationMarkerMiddleware(hash: string): unknown {
  const value = new Scalar(hash);
  value.type = 'QUOTE_DOUBLE';
  return { headers: { customRequestHeaders: { 'X-Bellhop-Generation': value } } };
}

// research.md R8: the backend URL scheme follows the same rule the Caddy and
// nginx drivers already apply -- https when the entry says its own
// certificate can't be verified, or when the backend port is the standard
// HTTPS one (443), plain http otherwise. With insecureTls the service names
// the shared bellhop-insecure-backend-tls transport (insecureSkipVerify);
// without it, Traefik's default transport verifies the certificate against
// the system CA pool for a 443 backend, matching Caddy's own behavior.
function backendUrl(backend: ProxyRoute['backend']): string {
  const scheme = backend.insecureTls || backend.port === 443 ? 'https' : 'http';
  return `${scheme}://${backend.ip}:${backend.port}`;
}

// A route's `Host(...) || Host(...)` expression alone, canonical first --
// used bare for the main router's rule, and wrapped in parens as the left
// side of the outpost/exempt routers' `&&` rules below (research.md R6).
function hostsRule(route: ProxyRoute): string {
  return route.hostnames.map((hostname) => `Host(${ruleValue(hostname)})`).join(' || ');
}

// One exempt pattern's own rule term -- Path() for an exact match,
// PathPrefix() for a prefix (research.md R6). pattern.path already ends in
// '/' for a prefix (parsePathPattern strips only the trailing '*'), so
// PathPrefix(`/api/`) is exactly what's wanted for a stored "/api/*".
function patternRule(pattern: PathPattern): string {
  return pattern.kind === 'exact' ? `Path(${ruleValue(pattern.path)})` : `PathPrefix(${ruleValue(pattern.path)})`;
}

const OUTPOST_PATH_PREFIX = '/outpost.goauthentik.io/';

// Every router's tls object by TLS source (issue #72, specs/
// 072-tls-source-setting/contracts/rendering-and-messages.md "Traefik"):
//   - acme-dns, acme-http: names ctx.certResolver, the resolver the
//     operator's static configuration defines (which challenge it uses is
//     configured there, not here);
//   - external: empty, so Traefik serves whatever default/static-config
//     certificate applies (its own self-signed default, or one supplied some
//     other way) -- byte-identical to the old reserved proxyCertResolver
//     'none' (issue #51, User Story 3);
//   - files: empty too -- the certificate comes from the top-level
//     tls.certificates entry render() adds (filesTlsSection), selected by SNI;
//   - internal: not supported -- a programming error (renderer backstop,
//     research R4; checkTlsSource refuses it first).
// One function so the main/outpost/exempt router sites below can never
// render this differently from one another.
function routerTls(ctx: ProxyContext): { certResolver?: string } {
  switch (ctx.tlsSource) {
    case 'acme-dns':
    case 'acme-http':
      return { certResolver: ctx.certResolver };
    case 'files':
    case 'external':
      return {};
    case 'internal':
      throw new Error("traefik driver cannot render tlsSource 'internal' (checkTlsSource should have refused it)");
  }
}

// The top-level dynamic-configuration tls section for tlsSource 'files'
// (issue #72, research R5): the shared ctx.tls pair, which Traefik's file
// provider adds to its default certificate store and selects by SNI for a
// router with tls: {}. No tls.stores default-certificate override is
// written, so an operator's own default store stays untouched. null under
// every other source -- nothing is rendered.
function filesTlsSection(ctx: ProxyContext): Record<string, unknown> | null {
  if (ctx.tlsSource !== 'files') return null;
  return { certificates: [{ certFile: ctx.tls.certificatePath, keyFile: ctx.tls.keyPath }] };
}

// The route's own forward-auth-only object names (research.md R7), from the
// same deduped, outpost-namespace-dropped exempt pattern list the nginx
// driver uses (candidateExemptPatterns, research.md R6): whether a bare '/*'
// is among them, and the patterns the exempt router matches. A '/*' drops
// bellhop-authentik from the main router, leaving it unauthenticated for
// every path -- so the exempt router is then suppressed entirely, whatever
// other patterns sit alongside it (research.md R9); there is nothing left
// for it to exempt.
function exemptPlan(route: ProxyRoute): { rootExempted: boolean; exemptTerms: PathPattern[] } {
  const patterns = candidateExemptPatterns(route);
  const rootExempted = patterns.some(isRootPrefix);
  return { rootExempted, exemptTerms: rootExempted ? [] : patterns };
}

// One route's own objects: the main router + service (contract "Rendered
// file: example", every entry's shape), plus, for a 'forward' route, its
// outpost router and (when any exempt pattern remains after dropping the
// outpost namespace and the root '/*') its exempt router (User Story 2,
// research.md R9). Router insertion order per route is route, outpost,
// exempt (per-route grouping in the contract example). The shared
// bellhop-authentik middleware and bellhop-authentik-outpost service this
// route's objects reference are emitted once by render() itself, not here.
function renderRouteObjects(
  route: ProxyRoute,
  ctx: ProxyContext,
  routers: Record<string, unknown>,
  services: Record<string, unknown>
): { usesInsecureTls: boolean } {
  const canonical = route.hostnames[0];
  const name = routeName(canonical);
  const hosts = hostsRule(route);
  const { rootExempted, exemptTerms } = exemptPlan(route);

  const middlewares = [...BASE_MIDDLEWARES];
  if (route.auth.mode === 'forward' && !rootExempted) {
    middlewares.push('bellhop-authentik');
  }

  routers[name] = {
    rule: hosts,
    entryPoints: ['websecure'],
    service: name,
    middlewares,
    tls: routerTls(ctx),
  };

  const loadBalancer: Record<string, unknown> = { servers: [{ url: backendUrl(route.backend) }] };
  if (route.backend.insecureTls) {
    loadBalancer.serversTransport = 'bellhop-insecure-backend-tls';
  }
  services[name] = { loadBalancer };

  if (route.auth.mode === 'forward') {
    // The outpost router is kept even when a bare '/*' removed
    // bellhop-authentik from the main router above -- the sign-in
    // redirect/callback it serves is still reachable regardless of what the
    // rest of the route exempts (research.md R9).
    routers[outpostName(canonical)] = {
      rule: `(${hosts}) && PathPrefix(${ruleValue(OUTPOST_PATH_PREFIX)})`,
      entryPoints: ['websecure'],
      service: 'bellhop-authentik-outpost',
      middlewares: [...BASE_MIDDLEWARES],
      tls: routerTls(ctx),
    };

    if (exemptTerms.length > 0) {
      routers[exemptName(canonical)] = {
        rule: `(${hosts}) && (${exemptTerms.map(patternRule).join(' || ')})`,
        entryPoints: ['websecure'],
        service: name,
        middlewares: [...BASE_MIDDLEWARES],
        tls: routerTls(ctx),
      };
    }
  }

  return { usesInsecureTls: route.backend.insecureTls };
}

// The forward-auth middleware and outpost service every forward-gated
// route's objects reference, emitted once (research.md R9) rather than
// per-route -- ctx.outpost is guaranteed set here: buildRoutes already
// throws the missing-authentik error before producing a 'forward' route
// when no authentik:true entry has an ip (same non-null convention the
// Caddy/nginx drivers already follow for their own outpost access).
function authentikMiddleware(ctx: ProxyContext): unknown {
  const outpostAddr = `${ctx.outpost!.ip}:${ctx.outpost!.port}`;
  return {
    forwardAuth: {
      address: `http://${outpostAddr}${OUTPOST_PATH_PREFIX}auth/traefik`,
      trustForwardHeader: true,
      authResponseHeaders: [...AUTHENTIK_IDENTITY_HEADERS],
    },
  };
}

function authentikOutpostService(ctx: ProxyContext): unknown {
  return { loadBalancer: { servers: [{ url: `http://${ctx.outpost!.ip}:${ctx.outpost!.port}` }] } };
}

// `lineWidth: 0` turns off the yaml package's default folding of long plain
// scalars at 80 columns: a folded rule parses the same, but a many-hostname
// rule split across lines reads badly in a dry-run preview and on the
// status page. Shared by both of render()'s stringify passes, so the hash
// input and the real output are always formatted alike.
const STRINGIFY_OPTIONS = { lineWidth: 0 };

const CONFIG_PATH_FIX = settingFix('proxyConfigPath', '/etc/traefik/dynamic/bellhop.yml');

// Traefik's file provider only loads files ending .yml/.yaml (or .toml, but
// Bellhop writes YAML), and a path ending in '/' names a directory -- either
// way Bellhop would write a file Traefik never reads, and nothing at Traefik's
// end reports it. SettingsSchema only requires an absolute path, so both are
// reachable through set-config; refused here with the same wording style as
// the HAProxy driver's own trailing-slash guard. Thrown from render(), so a
// dry run fails the same way an apply would.
function checkConfigPath(configPath: string): void {
  if (configPath.endsWith('/')) {
    throw new Error(
      `proxyConfigPath '${configPath}' ends in '/', but the Traefik driver needs a file path for its dynamic ` +
        `configuration file -- ${CONFIG_PATH_FIX}`
    );
  }
  if (!configPath.endsWith('.yml') && !configPath.endsWith('.yaml')) {
    throw new Error(
      `proxyConfigPath '${configPath}' does not end in .yml or .yaml, so Traefik's file provider would not load it ` +
        `(the Traefik driver writes YAML) -- ${CONFIG_PATH_FIX}`
    );
  }
}

// encodeHostname is injective only for valid DNS hostnames, and a subdomain
// is a plain string in the schema, so two routes can still encode to the
// same object names -- the second would silently overwrite the first's
// router and service. Refused instead, naming both hostnames.
function checkRouteNamesUnique(routes: ProxyRoute[]): void {
  const seen = new Map<string, string>();
  for (const route of routes) {
    const canonical = route.hostnames[0];
    const name = routeName(canonical);
    const previous = seen.get(name);
    if (previous !== undefined) {
      throw new Error(
        `The Traefik driver cannot render both '${previous}' and '${canonical}': their canonical hostnames ` +
          `encode to the same object name '${name}' -- rename one of the two subdomains`
      );
    }
    seen.set(name, canonical);
  }
}

// Renders every route into the one file this driver owns whole (contract
// "Rendered file: example"): the header comment, then a `http:` document
// built from the proxy-neutral ProxyRoute[]/ProxyContext buildRoutes/
// buildProxyContext have already derived, the same convention every other
// driver follows. `routers`/`services` are omitted entirely when empty
// (data-model.md), but `middlewares` always exists -- the header strip,
// bellhop-forwarded-port, and the generation marker, so the file is never
// actually empty even with zero routes (research.md R7, live-checked: a file
// with only middlewares loads fine).
//
// The marker's hash is the SHA-256 of the file rendered *without* the
// marker (research.md R3), so it is computed in two passes: build and
// stringify the document with every other object in place first, hash that
// text, then add the marker middleware (named after the hash) and stringify
// again for the real output. This is what makes the hash change whenever
// anything else about the file changes, and stay stable otherwise. Both
// passes use STRINGIFY_OPTIONS, so a long rule is never folded across lines.
export function render(routes: ProxyRoute[], ctx: ProxyContext, configPath: string): FileSpec[] {
  checkConfigPath(configPath);
  checkRouteNamesUnique(routes);

  const routers: Record<string, unknown> = {};
  const services: Record<string, unknown> = {};
  const middlewares: Record<string, unknown> = {
    'bellhop-strip-authentik-headers': stripAuthentikHeadersMiddleware(),
    'bellhop-forwarded-port': forwardedPortMiddleware(ctx),
  };
  let anyInsecureTls = false;

  for (const route of routes) {
    const { usesInsecureTls } = renderRouteObjects(route, ctx, routers, services);
    anyInsecureTls = anyInsecureTls || usesInsecureTls;
  }

  // bellhop-authentik and bellhop-authentik-outpost are shared across every
  // forward-gated route's own objects -- emitted once, after every route's
  // own router/service, only when at least one 'forward' route exists
  // (research.md R7/R9). bellhop-authentik is inserted right after
  // bellhop-forwarded-port in http.middlewares, ahead of the generation
  // marker buildHttp appends last.
  if (routes.some((route) => route.auth.mode === 'forward')) {
    middlewares['bellhop-authentik'] = authentikMiddleware(ctx);
    services['bellhop-authentik-outpost'] = authentikOutpostService(ctx);
  }

  const serversTransports: Record<string, unknown> = anyInsecureTls
    ? { 'bellhop-insecure-backend-tls': { insecureSkipVerify: true } }
    : {};

  function buildHttp(withMarker: Record<string, unknown> | null): Record<string, unknown> {
    const http: Record<string, unknown> = {};
    if (Object.keys(routers).length > 0) http.routers = routers;
    if (Object.keys(services).length > 0) http.services = services;
    http.middlewares = withMarker ? { ...middlewares, ...withMarker } : middlewares;
    if (Object.keys(serversTransports).length > 0) http.serversTransports = serversTransports;
    return http;
  }

  // tlsSource 'files' adds a top-level tls: section after http: (issue #72,
  // research R5) -- in both passes, so the generation hash covers it.
  const tlsSection = filesTlsSection(ctx);
  function buildDocument(withMarker: Record<string, unknown> | null): Record<string, unknown> {
    const doc: Record<string, unknown> = { http: buildHttp(withMarker) };
    if (tlsSection !== null) doc.tls = tlsSection;
    return doc;
  }

  const contentWithoutMarker = `${HEADER}\n${stringify(buildDocument(null), STRINGIFY_OPTIONS)}`;
  const hash = createHash('sha256').update(contentWithoutMarker).digest('hex').slice(0, 12);
  const markerName = `bellhop-generation-${hash}`;
  const content = `${HEADER}\n${stringify(buildDocument({ [markerName]: generationMarkerMiddleware(hash) }), STRINGIFY_OPTIONS)}`;

  return [{ path: configPath, content, mode: 'owned', ownedHeader: HEADER, atomic: ATOMIC }];
}

// Parses a rendered file back into the router/middleware names User Story 3's
// API validate step needs -- both read `http.routers`/`http.middlewares`
// with `parse` (the same `yaml` package `render` writes with) rather than
// re-deriving names from ProxyRoute[], so the validate step always checks
// exactly what the file on disk actually contains, not what a caller thinks
// it should contain.

// The one middleware among http.middlewares whose name starts with the
// generation-marker prefix -- exactly one is ever rendered (see render()
// above), so a file this driver produced always has one.
export function generationMarkerName(content: string): string {
  const doc = parse(content) as { http?: { middlewares?: Record<string, unknown> } } | null;
  const names = Object.keys(doc?.http?.middlewares ?? {});
  const marker = names.find((name) => name.startsWith('bellhop-generation-'));
  if (marker === undefined) {
    throw new Error('Rendered Traefik configuration has no generation-marker middleware');
  }
  return marker;
}

// Every router name, in the order render() wrote them (an object's own key
// order is preserved by both `stringify` and `parse`).
export function routerNames(content: string): string[] {
  const doc = parse(content) as { http?: { routers?: Record<string, unknown> } } | null;
  return Object.keys(doc?.http?.routers ?? {});
}

// User Story 3 / research.md R2-R4/R12: the opt-in post-write API check sent
// as the apply script's validate step (contracts/traefik-driver.md "Validate
// step (proxyApiUrl set)") when proxyApiUrl is configured. POSIX sh only --
// the proxy host may be an LXC guest (see CLAUDE.md's runRemote note). Runs
// as one subshell: first polls the file's own generation marker (R3) until
// it answers 200, proving Traefik has loaded *this* rendered version (and
// not a stale one, or none at all after a whole-file rejection, R2); then
// fetches every router this file declares by exact name and requires
// `"status":"enabled"` in its body, collecting every unhealthy router before
// failing so a multi-router misconfiguration is reported in full rather than
// one router at a time across repeated applies (R4). `content` is the
// rendered file's own text -- the marker/router names are parsed back out of
// it (generationMarkerName/routerNames) rather than re-derived from
// ProxyRoute[], so the check always matches exactly what was written, not
// what a caller thinks it wrote.
//
// Note on `set -e`: real curl exits non-zero on a connection failure/
// timeout (e.g. 7/28), even though it still writes '000' (via -w) or
// nothing (the plain router fetch, no -o) to stdout first. A bare
// `var="$(curl ...)"` is, per POSIX, a "simple command" whose own exit
// status is that of its last command substitution, which could in
// principle trip `set -e` -- but `buildFileDriverScript` always sends this
// whole function's output as the condition of `if ! ${validateCommand};
// then` (file-driver.ts), and POSIX/every shell tested (bash's sh mode,
// live curl; real dash, per code review) exempts a command's failure from
// triggering -e when it's nested anywhere inside a compound command being
// used as an if/while/until condition -- confirmed live with a real
// unreachable curl call nested exactly this way (a -e abort would have
// skipped straight past the retry loop with no diagnostic; it didn't).
// Verified by the executed tests below with a stub curl that mirrors real
// curl's own non-zero exit on the unreachable/router-fetch-failure paths.
const CURL_MISSING_MESSAGE =
  'curl is not installed on the proxy host; the Traefik API check (proxyApiUrl) needs it -- install curl there, or unset proxyApiUrl';

export function buildApiCheck(apiUrl: string, configPath: string, content: string): string {
  const api = apiUrl.replace(/\/+$/, '');
  const marker = generationMarkerName(content);
  const routers = routerNames(content);

  const lines: string[] = [
    '(',
    // Checked first: without curl every poll below would fail with "command
    // not found" and the check would end in a misleading load timeout.
    '  if ! command -v curl >/dev/null 2>&1; then',
    `    printf '%s\\n' ${singleQuote(CURL_MISSING_MESSAGE)} >&2`,
    '    exit 1',
    '  fi',
    `  bellhop_api=${singleQuote(api)}`,
    '  bellhop_tries=0',
    '  while :; do',
    `    bellhop_code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "$bellhop_api/api/http/middlewares/${marker}@file")"`,
    '    [ "$bellhop_code" = "200" ] && break',
    '    bellhop_tries=$((bellhop_tries + 1))',
    '    if [ "$bellhop_tries" -ge 30 ]; then',
    '      if [ "$bellhop_code" = "000" ]; then',
    '        bellhop_result="unreachable"',
    '      else',
    '        bellhop_result="HTTP $bellhop_code"',
    '      fi',
    // "30 checks one second apart", not "30 seconds": each check can itself
    // take up to --max-time 5, so the wall-clock wait is longer than 30s
    // whenever the API is slow to answer (research.md R4).
    `      printf 'Traefik did not load %s after 30 checks one second apart (%s at %s)\\n' ${singleQuote(configPath)} "$bellhop_result" "$bellhop_api" >&2`,
    '      exit 1',
    '    fi',
    '    sleep 1',
    '  done',
    '  bellhop_failed=0',
  ];

  for (const router of routers) {
    lines.push(`  bellhop_body="$(curl -s --max-time 5 "$bellhop_api/api/http/routers/${router}@file")"`);
    lines.push('  case "$bellhop_body" in');
    lines.push(`    *'"status":"enabled"'*) ;;`);
    lines.push(
      `    *) printf 'Traefik router %s is not healthy: %s\\n' ${singleQuote(router)} "$bellhop_body" >&2; bellhop_failed=1 ;;`
    );
    lines.push('  esac');
  }

  lines.push('  exit "$bellhop_failed"');
  lines.push(')');
  return lines.join('\n');
}

// The read-only API check (#87): one request, no retry (unlike buildApiCheck,
// which waits for a file it just wrote to load) -- a proxy that is already
// running answers at once.
export function buildApiPing(apiUrl: string): string {
  const api = apiUrl.replace(/\/+$/, '');
  return [
    'if ! command -v curl >/dev/null 2>&1; then',
    `  printf '%s\\n' ${singleQuote(CURL_MISSING_MESSAGE)} >&2`,
    '  exit 1',
    'fi',
    `bellhop_code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 ${singleQuote(`${api}/api/overview`)})" || true`,
    'if [ "$bellhop_code" != "200" ]; then',
    `  printf 'Traefik API at %s answered HTTP %s (000 means no answer)\\n' ${singleQuote(api)} "$bellhop_code" >&2`,
    '  exit 1',
    'fi',
  ].join('\n');
}

export const traefikDriver = fileDriver({
  id: 'traefik',
  label: 'Traefik',
  // Traefik's forward-auth and OIDC both work the same way every other
  // driver's do -- see User Story 2 for the forward-auth objects, not yet
  // rendered by this file.
  capabilities: { authModes: ['forward', 'oidc'], tlsSources: ['acme-dns', 'acme-http', 'files', 'external'], defaultTlsSource: 'acme-dns' },
  defaultConfigPath: '/etc/traefik/dynamic/bellhop.yml',
  // Traefik has no static-file server of its own (research.md R11) -- an
  // operator who wants a status page serves it elsewhere.
  statusPage: null,
  usesCertResolver: true,
  usesApiUrl: true,
  configPathNote:
    "Traefik's file provider must watch this file's directory. The whole file is replaced on every apply, and a file Bellhop didn't generate is refused.",
  render,
  // Opt-in (research.md R2): with no proxyApiUrl set there is nothing to
  // check, so the apply script writes and lets Traefik's own watcher pick
  // the file up with no validate step at all. files[0].content is the
  // driver's own single rendered FileSpec (render() above always returns
  // exactly one) -- buildApiCheck reads the marker/router names back out of
  // it rather than re-deriving them from routes, so the check always
  // matches exactly what was written.
  validateCommand: (path, { files, inventory }) =>
    inventory.proxyApiUrl ? buildApiCheck(inventory.proxyApiUrl, path, files[0].content) : null,
  validateLabel: 'Traefik API check',
  // Traefik's file-provider watcher reloads on its own once the write
  // lands -- there is no reload command to run.
  reloadCommand: null,
  // Read-only (#87): the watched directory must exist; with proxyApiUrl set,
  // Traefik's own API must answer, which proves it is running and reachable
  // from the proxy host.
  check: {
    target: 'directory',
    command: (_configPath, { inventory }) => (inventory.proxyApiUrl ? buildApiPing(inventory.proxyApiUrl) : null),
  },
});
