// User Story 1 (issue #32): the HAProxy driver's two files, pinned against
// specs/015-haproxy-proxy-driver/contracts/haproxy-config.md, plus its
// metadata, plan/apply/snapshot over a FakeSSHClient, and executed-script
// tests proving the two-file 'owned' delivery path restores both files.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, chmodSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, delimiter } from 'node:path';
import { spawnSync } from 'node:child_process';
import type { Inventory } from '../../../../src/lib/inventory.ts';
import { buildRoutes, buildProxyContext, type ProxyContext, type ProxyRoute } from '../../../../src/lib/proxy/routes.ts';
import { backendNames, haproxyDriver, mapPath, render } from '../../../../src/lib/proxy/drivers/haproxy.ts';
import type { FileSpec } from '../../../../src/lib/proxy/file-driver.ts';
import { FakeSSHClient } from '../../../support/fake-ssh-client.ts';

const HEADER = '# Generated by Bellhop sync-proxy for HAProxy. Do not edit: this file is replaced on every apply.';
// The nginx driver's own header -- deliberately different from HAProxy's, so
// a file the nginx driver left at a shared proxyConfigPath is refused.
const NGINX_HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';
const CONFIG_PATH = '/etc/haproxy/bellhop.cfg';
const MAP_PATH = '/etc/haproxy/bellhop.map';

// The contract's own example inventory ("Example"): an ungated guest with
// two hostnames, an insecureBackendTls host on 8006 (also the proxy host),
// and an OIDC-gated external site on 443.
function exampleInventory(): Inventory {
  return {
    domain: 'example.com',
    hosts: [
      {
        name: 'pve1',
        ssh_target: '192.0.2.2',
        ssh_user: 'root',
        proxy: true,
        ip: '192.0.2.2',
        port: 8006,
        subdomains: ['pve'],
        insecureBackendTls: true,
      },
    ],
    guests: [
      { name: 'web-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.10', port: 8080, subdomains: ['web', 'www'] },
    ],
    externalSites: [
      {
        name: 'nas',
        ip: '192.0.2.20',
        port: 443,
        subdomains: ['nas'],
        authGroup: 'bellhop-admin-family',
        authMode: 'oidc',
        oidcRedirectUris: ['https://nas.example.com/callback'],
      },
    ],
  };
}

function emptyInventory(): Inventory {
  return {
    domain: 'example.com',
    hosts: [{ name: 'pve1', ssh_target: '192.0.2.2', ssh_user: 'root', proxy: true }],
    guests: [],
  };
}

function renderInventory(inventory: Inventory, configPath = CONFIG_PATH): FileSpec[] {
  return render(buildRoutes(inventory), buildProxyContext(inventory, haproxyDriver), configPath);
}

// One backend block (contract "Backend block") -- the lines every backend
// shares, then the server line.
function backendBlock(name: string, externalPort: number, serverLine: string): string[] {
  return [
    `backend ${name}`,
    '    mode http',
    '    timeout server 1d',
    '    timeout tunnel 1d',
    '    http-request del-header x-authentik- -m beg',
    '    http-request set-header X-Forwarded-For %[src]',
    '    http-request set-header X-Forwarded-Proto https',
    '    http-request set-header X-Forwarded-Host %[req.hdr(host)]',
    `    http-request set-header X-Forwarded-Port ${externalPort}`,
    serverLine,
  ];
}

const EXPECTED_BACKENDS = [
  HEADER,
  '',
  ...backendBlock('bellhop_host_pve1', 443, '    server app 192.0.2.2:8006 ssl verify none'),
  '',
  ...backendBlock('bellhop_guest_web-lxc', 443, '    server app 192.0.2.10:8080'),
  '',
  ...backendBlock(
    'bellhop_externalSite_nas',
    443,
    '    server app 192.0.2.20:443 ssl verify required ca-file /etc/ssl/certs/ca-certificates.crt'
  ),
].join('\n');

const EXPECTED_MAP = [
  HEADER,
  'pve.example.com bellhop_host_pve1',
  'web.example.com bellhop_guest_web-lxc',
  'www.example.com bellhop_guest_web-lxc',
  'nas.example.com bellhop_externalSite_nas',
].join('\n');

function ctx(externalPort = 443): ProxyContext {
  return {
    externalPort,
    tls: {
      certificatePath: '/etc/letsencrypt/live/example.com/fullchain.pem',
      keyPath: '/etc/letsencrypt/live/example.com/privkey.pem',
    },
    certResolver: 'cloudflare',
    tlsSource: 'external',
    acmeDnsProvider: 'cloudflare',
  };
}

function route(overrides: Partial<ProxyRoute> & { owner: ProxyRoute['owner'] }): ProxyRoute {
  return {
    hostnames: [`${overrides.owner.name}.example.com`],
    backend: { ip: '192.0.2.30', port: 80, insecureTls: false },
    auth: { mode: 'ungated' },
    ...overrides,
  };
}

// --- T002: render ------------------------------------------------------------

test('render: the contract example -> exact backends and map files', () => {
  const [backends, map] = renderInventory(exampleInventory());
  assert.equal(backends.content, EXPECTED_BACKENDS);
  assert.equal(map.content, EXPECTED_MAP);
});

test('render: zero routes -> each file is exactly the header line', () => {
  const [backends, map] = renderInventory(emptyInventory());
  assert.equal(backends.content, HEADER);
  assert.equal(map.content, HEADER);
});

test('render returns two owned FileSpecs -- backends at configPath, then the map beside it -- each owned by its first line', () => {
  const files = renderInventory(exampleInventory());
  assert.equal(files.length, 2);
  assert.deepEqual(
    files.map((f) => f.path),
    [CONFIG_PATH, MAP_PATH]
  );
  for (const file of files) {
    assert.equal(file.mode, 'owned');
    assert.equal(file.ownedHeader, HEADER);
    assert.equal(file.content.split('\n')[0], file.ownedHeader);
  }
});

test("render: an OIDC route renders identically to the same route ungated (no auth lines at all)", () => {
  const ungated = exampleInventory();
  ungated.externalSites = [{ name: 'nas', ip: '192.0.2.20', port: 443, subdomains: ['nas'] }];
  assert.deepEqual(renderInventory(exampleInventory()), renderInventory(ungated));
});

test("render: a forward-gated route throws naming the entry (the capability check's backstop)", () => {
  const forward = route({
    owner: { type: 'guest', name: 'app-lxc' },
    auth: { mode: 'forward', exemptPaths: [], rawExemptPaths: [] },
  });
  assert.throws(() => render([forward], ctx(), CONFIG_PATH), /^Error: HAProxy cannot enforce forward-auth for entry 'app-lxc'$/);
});

test('render: X-Forwarded-Port follows ctx.externalPort', () => {
  const [backends] = render([route({ owner: { type: 'guest', name: 'app-lxc' } })], ctx(8443), CONFIG_PATH);
  assert.match(backends.content, /^ {4}http-request set-header X-Forwarded-Port 8443$/m);
  assert.doesNotMatch(backends.content, /X-Forwarded-Port 443$/m);
});

test('render: map hostnames are lower-cased, canonical first; backend names keep their case', () => {
  const r = route({ owner: { type: 'guest', name: 'App-LXC' }, hostnames: ['App.Example.com', 'ALIAS.example.com'] });
  const [backends, map] = render([r], ctx(), CONFIG_PATH);
  assert.equal(map.content, [HEADER, 'app.example.com bellhop_guest_App-LXC', 'alias.example.com bellhop_guest_App-LXC'].join('\n'));
  assert.match(backends.content, /^backend bellhop_guest_App-LXC$/m);
});

test('render: never renders unauthenticatedPaths (an OIDC entry that also carries them)', () => {
  const inv = exampleInventory();
  inv.externalSites![0].unauthenticatedPaths = ['/api/*'];
  const [backends, map] = renderInventory(inv);
  assert.doesNotMatch(backends.content + map.content, /\/api/);
});

// --- US2 (issue #32, T013): forward-gated entries are refused, never emitted ---

test('render: an OIDC route with saved unauthenticatedPaths renders byte-identically to the same route without them', () => {
  const withPaths = exampleInventory();
  withPaths.externalSites![0].unauthenticatedPaths = ['/api/*', '/health'];
  const withoutPaths = exampleInventory();
  assert.deepEqual(renderInventory(withPaths), renderInventory(withoutPaths));
});

test('mapPath: bellhop.map in configPath\'s own directory', () => {
  assert.equal(mapPath('/etc/haproxy/bellhop.cfg'), '/etc/haproxy/bellhop.map');
  assert.equal(mapPath('/opt/haproxy/sites.cfg'), '/opt/haproxy/bellhop.map');
  assert.equal(mapPath('/bellhop.cfg'), '/bellhop.map');
});

test('render: a configPath in another directory puts the map beside it', () => {
  const files = renderInventory(exampleInventory(), '/opt/haproxy/sites.cfg');
  assert.deepEqual(
    files.map((f) => f.path),
    ['/opt/haproxy/sites.cfg', '/opt/haproxy/bellhop.map']
  );
});

test('render: throws naming proxyConfigPath when configPath is itself the map path', () => {
  assert.throws(() => renderInventory(exampleInventory(), '/etc/haproxy/bellhop.map'), (err: Error) => {
    assert.match(err.message, /proxyConfigPath/);
    assert.match(err.message, /\/etc\/haproxy\/bellhop\.map/);
    return true;
  });
});

test("render: the HAProxy header differs from the nginx driver's, so neither driver replaces the other's file", () => {
  const [backends, map] = renderInventory(exampleInventory());
  assert.notEqual(backends.ownedHeader, NGINX_HEADER);
  assert.notEqual(map.ownedHeader, NGINX_HEADER);
});

test('render: every backend strips client-supplied X-authentik-* headers as its first http-request rule', () => {
  const [backends] = renderInventory(exampleInventory());
  const blocks = backends.content.split('\n\n').slice(1);
  assert.equal(blocks.length, 3);
  for (const block of blocks) {
    const httpRequest = block.split('\n').filter((l) => l.trimStart().startsWith('http-request'));
    assert.equal(httpRequest[0], '    http-request del-header x-authentik- -m beg');
  }
});

test('render: the map-path guard also catches a non-normalised configPath naming the map file', () => {
  for (const configPath of ['/etc/haproxy//bellhop.map', '/etc/haproxy/./bellhop.map']) {
    assert.throws(() => renderInventory(exampleInventory(), configPath), (err: Error) => {
      assert.match(err.message, /proxyConfigPath/);
      assert.ok(err.message.includes(configPath), `names '${configPath}'`);
      return true;
    });
  }
});

test('render: a configPath ending in / throws naming proxyConfigPath instead of writing the map one directory up', () => {
  assert.throws(() => renderInventory(exampleInventory(), '/etc/haproxy/'), (err: Error) => {
    assert.match(err.message, /proxyConfigPath/);
    assert.ok(err.message.includes("'/etc/haproxy/'"));
    return true;
  });
});

// --- T003: backend names -----------------------------------------------------

test('backendNames: bellhop_<ownerType>_<name> for each owner type', () => {
  const names = backendNames([
    route({ owner: { type: 'host', name: 'pve1' } }),
    route({ owner: { type: 'guest', name: 'web-lxc' } }),
    route({ owner: { type: 'externalSite', name: 'nas' } }),
  ]);
  assert.deepEqual(names, ['bellhop_host_pve1', 'bellhop_guest_web-lxc', 'bellhop_externalSite_nas']);
});

test('backendNames: characters outside [A-Za-z0-9_.:-] become _', () => {
  assert.deepEqual(backendNames([route({ owner: { type: 'externalSite', name: 'a/b c' } })]), ['bellhop_externalSite_a_b_c']);
  assert.deepEqual(backendNames([route({ owner: { type: 'guest', name: 'ok_.:-Z9' } })]), ['bellhop_guest_ok_.:-Z9']);
});

test('backendNames: a host and a guest with the same name get distinct names', () => {
  const names = backendNames([route({ owner: { type: 'host', name: 'box' } }), route({ owner: { type: 'guest', name: 'box' } })]);
  assert.deepEqual(names, ['bellhop_host_box', 'bellhop_guest_box']);
});

test('backendNames: two names that sanitise to the same backend name get _2 on the later route, _3 after that', () => {
  const names = backendNames([
    route({ owner: { type: 'externalSite', name: 'a b' } }),
    route({ owner: { type: 'externalSite', name: 'a/b' } }),
    route({ owner: { type: 'externalSite', name: 'a+b' } }),
  ]);
  assert.deepEqual(names, ['bellhop_externalSite_a_b', 'bellhop_externalSite_a_b_2', 'bellhop_externalSite_a_b_3']);
});

test('backendNames: a suffixed name never collides with a name an earlier route already holds', () => {
  const names = backendNames([
    route({ owner: { type: 'guest', name: 'a_b_2' } }),
    route({ owner: { type: 'guest', name: 'a b' } }),
    route({ owner: { type: 'guest', name: 'a/b' } }),
  ]);
  assert.deepEqual(names, ['bellhop_guest_a_b_2', 'bellhop_guest_a_b', 'bellhop_guest_a_b_3']);
});

test('render: the map and backends files use the same collision-suffixed name for each route', () => {
  const routes = [
    route({ owner: { type: 'externalSite', name: 'a b' }, hostnames: ['one.example.com'] }),
    route({ owner: { type: 'externalSite', name: 'a/b' }, hostnames: ['two.example.com'] }),
  ];
  const [backends, map] = render(routes, ctx(), CONFIG_PATH);
  assert.match(backends.content, /^backend bellhop_externalSite_a_b$/m);
  assert.match(backends.content, /^backend bellhop_externalSite_a_b_2$/m);
  assert.equal(
    map.content,
    [HEADER, 'one.example.com bellhop_externalSite_a_b', 'two.example.com bellhop_externalSite_a_b_2'].join('\n')
  );
});

// --- T004: driver metadata ---------------------------------------------------

test('haproxyDriver declares its id, label, capabilities, default config path, status page and config path note', () => {
  assert.equal(haproxyDriver.id, 'haproxy');
  assert.equal(haproxyDriver.label, 'HAProxy');
  assert.deepEqual(haproxyDriver.capabilities.authModes, ['oidc']);
  assert.equal(haproxyDriver.defaultConfigPath, '/etc/haproxy/bellhop.cfg');
  assert.equal(haproxyDriver.statusPage, null);
  assert.deepEqual(haproxyDriver.capabilities.tlsSources, ['external']);
  assert.equal(
    haproxyDriver.configPathNote,
    "HAProxy replaces this whole file and writes bellhop.map beside it on every apply, and refuses to replace a file it didn't generate."
  );
});

// --- T005: plan / apply / snapshot over a FakeSSHClient -----------------------

function deps(ssh: FakeSSHClient, configPath = CONFIG_PATH) {
  return { ssh, inventory: exampleInventory(), proxyHost: 'pve1', configPath };
}

test('plan(): preview is the backends file then the map file, each under a ==> <path> <== label, and the payload is both FileSpecs', async () => {
  const inv = exampleInventory();
  const ssh = new FakeSSHClient(() => ({ stdout: '', stderr: '', code: 0 }));
  const plan = await haproxyDriver.plan(buildRoutes(inv), buildProxyContext(inv, haproxyDriver), deps(ssh));
  assert.equal(
    plan.preview,
    `==> ${CONFIG_PATH} <==\n${EXPECTED_BACKENDS}\n\n==> ${MAP_PATH} <==\n${EXPECTED_MAP}`
  );
  assert.deepEqual(
    (plan.payload as FileSpec[]).map((f) => f.content),
    [EXPECTED_BACKENDS, EXPECTED_MAP],
    'the payload carries no preview labels'
  );
  assert.deepEqual(
    (plan.payload as FileSpec[]).map((f) => f.path),
    [CONFIG_PATH, MAP_PATH]
  );
  assert.equal(ssh.history.length, 0, 'plan makes no SSH call');
});

test('apply(): one script to the proxy host that writes both files, validates with haproxy -c over both configs, then reloads', async () => {
  const inv = exampleInventory();
  const ssh = new FakeSSHClient(() => ({ stdout: '', stderr: '', code: 0 }));
  const d = deps(ssh);
  const plan = await haproxyDriver.plan(buildRoutes(inv), buildProxyContext(inv, haproxyDriver), d);
  await haproxyDriver.apply(plan, d);
  assert.equal(ssh.history.length, 1);
  assert.equal(ssh.history[0].sshTarget, '192.0.2.2');
  const script = ssh.history[0].command;
  assert.match(script, /cat > '\/etc\/haproxy\/bellhop\.cfg' <</);
  assert.match(script, /cat > '\/etc\/haproxy\/bellhop\.map' <</);
  assert.ok(
    script.includes("if ! haproxy -c -f /etc/haproxy/haproxy.cfg -f '/etc/haproxy/bellhop.cfg'; then"),
    'validates the operator main config together with the backends file'
  );
  assert.match(script, /^systemctl reload haproxy$/m);
});

test('apply(): a non-zero exit throws with the remote stderr', async () => {
  const inv = exampleInventory();
  const ssh = new FakeSSHClient(() => ({ stdout: '', stderr: 'haproxy -c failed', code: 1 }));
  const d = deps(ssh);
  const plan = await haproxyDriver.plan(buildRoutes(inv), buildProxyContext(inv, haproxyDriver), d);
  await assert.rejects(() => haproxyDriver.apply(plan, d), /haproxy -c failed/);
});

test('snapshot(): cats both files with ==> <path> <== headers', async () => {
  const ssh = new FakeSSHClient(() => ({ stdout: 'both files', stderr: '', code: 0 }));
  const out = await haproxyDriver.snapshot(deps(ssh));
  assert.equal(out, 'both files');
  assert.equal(ssh.history.length, 1);
  assert.equal(
    ssh.history[0].command,
    "echo '==> /etc/haproxy/bellhop.cfg <=='; cat '/etc/haproxy/bellhop.cfg'; " +
      "echo '==> /etc/haproxy/bellhop.map <=='; cat '/etc/haproxy/bellhop.map'"
  );
});

test('snapshot(): follows a custom proxyConfigPath for both files', async () => {
  const ssh = new FakeSSHClient(() => ({ stdout: '', stderr: '', code: 0 }));
  await haproxyDriver.snapshot(deps(ssh, '/opt/haproxy/sites.cfg'));
  assert.match(ssh.history[0].command, /cat '\/opt\/haproxy\/sites\.cfg'/);
  assert.match(ssh.history[0].command, /cat '\/opt\/haproxy\/bellhop\.map'/);
});

// --- T006: executed-script tests (the real apply() script under sh) ----------

function shAvailable(): boolean {
  const result = spawnSync('sh', ['-c', 'exit 0']);
  return result.error === undefined || result.error === null;
}

interface ExecutedApply {
  status: number | null;
  stderr: string;
  cfgPath: string;
  mapFilePath: string;
  haproxyLogPath: string;
  systemctlLogPath: string;
  files: FileSpec[];
}

// Captures the exact script haproxyDriver.apply() sends (through a
// FakeSSHClient), then runs it locally under sh with stub haproxy and
// systemctl binaries first on PATH -- the file-driver executed-script
// exception CLAUDE.md allows. The haproxy stub logs its arguments and exits
// with the given code.
async function runApply(opts: { cfg?: string; map?: string; haproxyExit: number }): Promise<ExecutedApply> {
  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-haproxy-driver-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-haproxy-driver-stubs-'));
  const posix = (p: string) => p.replace(/\\/g, '/');
  const cfgPath = posix(join(tmpDir, 'bellhop.cfg'));
  const mapFilePath = posix(join(tmpDir, 'bellhop.map'));
  const haproxyLogPath = posix(join(tmpDir, 'haproxy.log'));
  const systemctlLogPath = posix(join(tmpDir, 'systemctl.log'));
  if (opts.cfg !== undefined) writeFileSync(cfgPath, opts.cfg);
  if (opts.map !== undefined) writeFileSync(mapFilePath, opts.map);

  const inv = exampleInventory();
  const ssh = new FakeSSHClient(() => ({ stdout: '', stderr: '', code: 0 }));
  const d = { ssh, inventory: inv, proxyHost: 'pve1', configPath: cfgPath };
  const plan = await haproxyDriver.plan(buildRoutes(inv), buildProxyContext(inv, haproxyDriver), d);
  await haproxyDriver.apply(plan, d);
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, ssh.history[0].command);

  const haproxyStub = join(stubDir, 'haproxy');
  writeFileSync(haproxyStub, `#!/bin/sh\necho "$@" >> '${haproxyLogPath}'\nexit ${opts.haproxyExit}\n`);
  chmodSync(haproxyStub, 0o755);
  const systemctlStub = join(stubDir, 'systemctl');
  writeFileSync(systemctlStub, `#!/bin/sh\necho "$@" >> '${systemctlLogPath}'\n`);
  chmodSync(systemctlStub, 0o755);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}` };
  const result = spawnSync('sh', [scriptPath], { env });
  return {
    status: result.status,
    stderr: String(result.stderr),
    cfgPath,
    mapFilePath,
    haproxyLogPath,
    systemctlLogPath,
    files: plan.payload as FileSpec[],
  };
}

const OLD_CFG = `${HEADER}\n\nbackend bellhop_guest_old\n    mode http\n    server app 192.0.2.99:80\n`;
const OLD_MAP = `${HEADER}\nold.example.com bellhop_guest_old\n`;

test('haproxyDriver apply script, executed: a failed "haproxy -c" restores both existing files byte for byte, exits non-zero, and never reloads', async (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }
  const run = await runApply({ cfg: OLD_CFG, map: OLD_MAP, haproxyExit: 1 });
  assert.notEqual(run.status, 0, `expected a non-zero exit, stderr: ${run.stderr}`);
  assert.equal(readFileSync(run.cfgPath, 'utf8'), OLD_CFG, 'the backends file must be restored byte for byte');
  assert.equal(readFileSync(run.mapFilePath, 'utf8'), OLD_MAP, 'the map file must be restored byte for byte');
  assert.ok(existsSync(run.haproxyLogPath), 'haproxy -c must have run');
  assert.ok(!existsSync(run.systemctlLogPath), 'systemctl must not have been called');
});

test('haproxyDriver apply script, executed: a failed "haproxy -c" removes a map file that did not exist before, and restores the backends file', async (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }
  const run = await runApply({ cfg: OLD_CFG, haproxyExit: 1 });
  assert.notEqual(run.status, 0, `expected a non-zero exit, stderr: ${run.stderr}`);
  assert.equal(readFileSync(run.cfgPath, 'utf8'), OLD_CFG);
  assert.ok(!existsSync(run.mapFilePath), 'a map file that did not exist before must be removed again');
  assert.ok(!existsSync(run.systemctlLogPath), 'systemctl must not have been called');
});

test('haproxyDriver apply script, executed: a passing "haproxy -c" writes both files and reloads haproxy once', async (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }
  const run = await runApply({ cfg: OLD_CFG, map: OLD_MAP, haproxyExit: 0 });
  assert.equal(run.status, 0, `expected exit 0, stderr: ${run.stderr}`);
  // The heredoc that writes an 'owned' file always ends with a newline.
  assert.equal(readFileSync(run.cfgPath, 'utf8'), `${run.files[0].content}\n`);
  assert.equal(readFileSync(run.mapFilePath, 'utf8'), `${run.files[1].content}\n`);
  assert.equal(readFileSync(run.haproxyLogPath, 'utf8').trim(), `-c -f /etc/haproxy/haproxy.cfg -f ${run.cfgPath}`);
  assert.equal(readFileSync(run.systemctlLogPath, 'utf8').trim(), 'reload haproxy');
});

test('haproxyDriver apply script, executed: an existing map file without the generated header is refused before writing, leaving both files untouched', async (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }
  const foreignMap = 'example.com some_other_backend\n';
  const run = await runApply({ cfg: OLD_CFG, map: foreignMap, haproxyExit: 0 });
  assert.notEqual(run.status, 0, `expected a non-zero exit, stderr: ${run.stderr}`);
  assert.equal(readFileSync(run.cfgPath, 'utf8'), OLD_CFG, 'the backends file must be untouched');
  assert.equal(readFileSync(run.mapFilePath, 'utf8'), foreignMap, 'the foreign map file must be untouched');
  assert.ok(!existsSync(run.haproxyLogPath), 'haproxy -c must not have run');
  assert.ok(!existsSync(run.systemctlLogPath), 'systemctl must not have been called');
  assert.ok(run.stderr.includes(run.mapFilePath), 'the refusal names the map path');
  assert.match(run.stderr, /proxyConfigPath/);
});

test('haproxyDriver apply script, executed: an existing backends file carrying the nginx driver header is refused before writing, leaving both files untouched', async (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }
  const nginxFile = `${NGINX_HEADER}\n\nserver {\n    listen 443 ssl;\n}\n`;
  const run = await runApply({ cfg: nginxFile, map: OLD_MAP, haproxyExit: 0 });
  assert.notEqual(run.status, 0, `expected a non-zero exit, stderr: ${run.stderr}`);
  assert.equal(readFileSync(run.cfgPath, 'utf8'), nginxFile, 'the nginx-owned file must be untouched');
  assert.equal(readFileSync(run.mapFilePath, 'utf8'), OLD_MAP, 'the map file must be untouched');
  assert.ok(!existsSync(run.haproxyLogPath), 'haproxy -c must not have run');
  assert.ok(!existsSync(run.systemctlLogPath), 'systemctl must not have been called');
  assert.ok(run.stderr.includes(run.cfgPath), 'the refusal names the backends file path');
});
