// User Story 1 (issue #30): render tests pinned against
// specs/009-nginx-proxy-driver/contracts/nginx-config.md, plus one executed
// -script test proving the 'owned'-mode delivery path (research R9) --
// forward-gated rendering is User Story 2's job (test/lib/proxy/drivers/
// nginx.test.ts grows those cases in that phase; this file only has to
// prove a forward-gated route renders no differently from an ungated one
// for now, per the task brief).
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, chmodSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, delimiter } from 'node:path';
import { spawnSync } from 'node:child_process';
import type { Inventory } from '../../../../src/lib/inventory.ts';
import { buildRoutes, buildProxyContext } from '../../../../src/lib/proxy/routes.ts';
import { nginxDriver, render } from '../../../../src/lib/proxy/drivers/nginx.ts';
import { buildFileDriverScript, type FileSpec } from '../../../../src/lib/proxy/file-driver.ts';

const HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';
const MAP_BLOCKS = [
  'map $http_upgrade $bellhop_connection_upgrade {',
  '    default upgrade;',
  "    ''      '';",
  '}',
  '',
  'map $http_host $bellhop_http_host {',
  '    default $http_host;',
  "    ''      $host;",
  '}',
].join('\n');

// The file's fixed shape (contract "File skeleton"), present even with no
// routes at all -- render's shape never depends on the inventory.
const SKELETON = `${HEADER}\n\n${MAP_BLOCKS}`;

function inv(overrides: Partial<Inventory> = {}): Inventory {
  return {
    domain: 'example.com',
    hosts: [{ name: 'pve1', ssh_target: '192.0.2.1', ssh_user: 'root', proxy: true }],
    guests: [],
    ...overrides,
  };
}

// Builds the same content sync-proxy would preview/write: buildRoutes/
// buildProxyContext have already done the derivation by the time render
// runs, exactly as fileDriver's plan() calls it.
function configOf(inventory: Inventory): string {
  return render(buildRoutes(inventory), buildProxyContext(inventory), '/etc/nginx/conf.d/bellhop.conf')[0].content;
}

// --- (a) skeleton, even with zero routes ------------------------------------

test('render: no routes -> the header comment plus both map blocks only', () => {
  assert.equal(configOf(inv()), SKELETON);
});

// --- (b) one ungated route with two subdomains ------------------------------

test('render: one ungated route with two subdomains -> full server block, canonical hostname first, quoted cert paths, and proxy lines', () => {
  const inventory = inv({
    guests: [
      { name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.10', port: 8080, subdomains: ['app', 'alias'] },
    ],
  });
  const expected = [
    SKELETON,
    '',
    'server {',
    '    listen 443 ssl;',
    '    listen [::]:443 ssl;',
    '    server_name app.example.com alias.example.com;',
    '',
    '    ssl_certificate "/etc/letsencrypt/live/example.com/fullchain.pem";',
    '    ssl_certificate_key "/etc/letsencrypt/live/example.com/privkey.pem";',
    '',
    '    client_max_body_size 0;',
    '    proxy_buffering off;',
    '',
    '    location / {',
    '        proxy_pass http://192.0.2.10:8080;',
    '        proxy_http_version 1.1;',
    '        proxy_set_header Host $bellhop_http_host;',
    '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
    '        proxy_set_header X-Forwarded-Proto $scheme;',
    '        proxy_set_header X-Forwarded-Host $bellhop_http_host;',
    '        proxy_set_header X-Forwarded-Port 443;',
    '        proxy_set_header Upgrade $http_upgrade;',
    '        proxy_set_header Connection $bellhop_connection_upgrade;',
    '    }',
    '}',
  ].join('\n');
  assert.equal(configOf(inventory), expected);
});

// --- (c) insecureBackendTls: true -------------------------------------------

test('render: insecureBackendTls -> https upstream with proxy_ssl_verify off, no CA bundle line', () => {
  const inventory = inv({
    guests: [
      {
        name: 'app-lxc',
        type: 'lxc',
        vmid: 100,
        host: 'pve1',
        ip: '192.0.2.11',
        port: 8443,
        subdomains: ['app'],
        insecureBackendTls: true,
      },
    ],
  });
  const content = configOf(inventory);
  assert.match(content, /proxy_pass https:\/\/192\.0\.2\.11:8443;/);
  assert.match(content, /proxy_ssl_verify off;/);
  assert.doesNotMatch(content, /proxy_ssl_verify on;/);
  assert.doesNotMatch(content, /proxy_ssl_trusted_certificate/);
});

// --- (d) port 443 without insecureBackendTls --------------------------------

test('render: port 443 without insecureBackendTls -> https upstream with proxy_ssl_verify on and the trusted CA bundle', () => {
  const inventory = inv({
    guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.12', port: 443, subdomains: ['app'] }],
  });
  const content = configOf(inventory);
  assert.match(content, /proxy_pass https:\/\/192\.0\.2\.12:443;/);
  assert.match(content, /proxy_ssl_verify on;/);
  assert.match(content, /proxy_ssl_trusted_certificate \/etc\/ssl\/certs\/ca-certificates\.crt;/);
  assert.doesNotMatch(content, /proxy_ssl_verify off;/);
});

// --- (e) authMode: 'oidc' renders identically to ungated --------------------

test("render: an authMode 'oidc' gated route renders identically to an ungated route (no auth_request, no outpost location)", () => {
  const ungated = configOf(
    inv({ guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.13', port: 80, subdomains: ['app'] }] })
  );
  const oidc = configOf(
    inv({
      guests: [
        {
          name: 'app-lxc',
          type: 'lxc',
          vmid: 100,
          host: 'pve1',
          ip: '192.0.2.13',
          port: 80,
          subdomains: ['app'],
          authGroup: 'bellhop-users',
          authMode: 'oidc',
        },
      ],
    })
  );
  assert.equal(oidc, ungated);
  assert.doesNotMatch(oidc, /auth_request/);
  assert.doesNotMatch(oidc, /outpost\.goauthentik\.io/);
});

// --- (f) two routes, one blank line between server blocks -------------------

test('render: two routes produce two server blocks separated by exactly one blank line', () => {
  const inventory = inv({
    guests: [
      { name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.14', port: 80, subdomains: ['app'] },
      { name: 'media-lxc', type: 'lxc', vmid: 101, host: 'pve1', ip: '192.0.2.15', port: 8096, subdomains: ['media'] },
    ],
  });
  const content = configOf(inventory);
  assert.match(content, /\}\n\nserver \{/, 'exactly one blank line separates the two server blocks');
  assert.equal((content.match(/^server \{/gm) ?? []).length, 2);
});

// --- (g) the returned FileSpec ------------------------------------------------

test('render returns exactly one owned FileSpec at configPath', () => {
  const inventory = inv({ guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.16', subdomains: ['app'] }] });
  const files = render(buildRoutes(inventory), buildProxyContext(inventory), '/etc/nginx/conf.d/bellhop.conf');
  assert.equal(files.length, 1);
  assert.equal(files[0].path, '/etc/nginx/conf.d/bellhop.conf');
  assert.equal(files[0].mode, 'owned');
});

// --- (h) driver metadata -----------------------------------------------------

test('nginxDriver declares its id, default config path, and capabilities', () => {
  assert.equal(nginxDriver.id, 'nginx');
  assert.equal(nginxDriver.defaultConfigPath, '/etc/nginx/conf.d/bellhop.conf');
  assert.deepEqual(nginxDriver.capabilities, { authModes: ['forward', 'oidc'], acmeDns01ViaCloudflare: false });
});

// --- executed-script test (research R9): the 'owned' delivery path ---------

function shAvailable(): boolean {
  const result = spawnSync('sh', ['-c', 'exit 0']);
  return result.error === undefined || result.error === null;
}

test('nginxDriver apply script, executed: a failed "nginx -t" restores an existing file byte for byte, exits non-zero, and never reloads', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }

  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-stubs-'));
  const posix = (p: string) => p.replace(/\\/g, '/');
  const confPath = posix(join(tmpDir, 'bellhop.conf'));
  const systemctlLogPath = posix(join(tmpDir, 'systemctl.log'));

  const originalContent = 'server {\n    server_name old.example.com;\n}';
  writeFileSync(confPath, originalContent);

  const newContent = 'server {\n    server_name new.example.com;\n}';
  const files: FileSpec[] = [{ path: confPath, content: newContent, mode: 'owned' }];
  const script = buildFileDriverScript(files, 'nginx -t', 'systemctl reload nginx');
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  const nginxFailPath = join(stubDir, 'nginx');
  writeFileSync(nginxFailPath, '#!/bin/sh\nexit 1\n');
  chmodSync(nginxFailPath, 0o755);
  const systemctlPath = join(stubDir, 'systemctl');
  writeFileSync(systemctlPath, `#!/bin/sh\necho "$@" >> '${systemctlLogPath}'\n`);
  chmodSync(systemctlPath, 0o755);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}` };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.equal(result.status, 1, `expected exit 1, got ${result.status}, stderr: ${result.stderr}`);
  assert.equal(readFileSync(confPath, 'utf8'), originalContent, 'the original file must be restored byte for byte');
  assert.ok(!existsSync(systemctlLogPath), 'systemctl must not have been called');
});

test('nginxDriver apply script, executed: a failed "nginx -t" removes a file that did not exist before, and never reloads', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }

  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-noexist-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-noexist-stubs-'));
  const posix = (p: string) => p.replace(/\\/g, '/');
  const confPath = posix(join(tmpDir, 'bellhop.conf'));
  const systemctlLogPath = posix(join(tmpDir, 'systemctl.log'));

  const newContent = 'server {\n    server_name new.example.com;\n}';
  const files: FileSpec[] = [{ path: confPath, content: newContent, mode: 'owned' }];
  const script = buildFileDriverScript(files, 'nginx -t', 'systemctl reload nginx');
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  const nginxFailPath = join(stubDir, 'nginx');
  writeFileSync(nginxFailPath, '#!/bin/sh\nexit 1\n');
  chmodSync(nginxFailPath, 0o755);
  const systemctlPath = join(stubDir, 'systemctl');
  writeFileSync(systemctlPath, `#!/bin/sh\necho "$@" >> '${systemctlLogPath}'\n`);
  chmodSync(systemctlPath, 0o755);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}` };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.equal(result.status, 1, `expected exit 1, got ${result.status}, stderr: ${result.stderr}`);
  assert.ok(!existsSync(confPath), 'a file that did not exist before must be removed on restore, not left behind');
  assert.ok(!existsSync(systemctlLogPath), 'systemctl must not have been called');
});

test('nginxDriver apply script, executed: a successful "nginx -t" writes the new content once and reloads nginx once', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }

  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-ok-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-ok-stubs-'));
  const posix = (p: string) => p.replace(/\\/g, '/');
  const confPath = posix(join(tmpDir, 'bellhop.conf'));
  const systemctlLogPath = posix(join(tmpDir, 'systemctl.log'));

  const originalContent = 'server {\n    server_name old.example.com;\n}';
  writeFileSync(confPath, originalContent);

  const newContent = 'server {\n    server_name new.example.com;\n}';
  const files: FileSpec[] = [{ path: confPath, content: newContent, mode: 'owned' }];
  const script = buildFileDriverScript(files, 'nginx -t', 'systemctl reload nginx');
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  const nginxOkPath = join(stubDir, 'nginx');
  writeFileSync(nginxOkPath, '#!/bin/sh\nexit 0\n');
  chmodSync(nginxOkPath, 0o755);
  const systemctlPath = join(stubDir, 'systemctl');
  writeFileSync(systemctlPath, `#!/bin/sh\necho "$@" >> '${systemctlLogPath}'\n`);
  chmodSync(systemctlPath, 0o755);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}` };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.equal(result.status, 0, `expected exit 0, got ${result.status}, stderr: ${result.stderr}`);
  // The heredoc buildFileDriverScript uses to write an 'owned' file always
  // ends with a newline (same as every other `cat <<'TAG'` in this script),
  // same convention the file-driver tests use for a managed-section file.
  assert.equal(readFileSync(confPath, 'utf8'), `${newContent}\n`, 'the new content must be written whole');
  assert.equal(readFileSync(systemctlLogPath, 'utf8').trim(), 'reload nginx', 'systemctl reload nginx must have run exactly once');
});
