// User Story 1 (issue #30): render tests pinned against
// specs/009-nginx-proxy-driver/contracts/nginx-config.md's "Ungated or OIDC
// route" section, plus one executed-script test proving the 'owned'-mode
// delivery path (research R9). User Story 2 (below, "Forward-gated routes")
// adds the Authentik forward-auth gating cases against that contract's
// "Forward-gated route" section.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, writeFileSync, chmodSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, delimiter } from 'node:path';
import { spawnSync } from 'node:child_process';
import type { Inventory } from '../../../../src/lib/inventory.ts';
import { buildRoutes, buildProxyContext } from '../../../../src/lib/proxy/routes.ts';
import { nginxDriver, render } from '../../../../src/lib/proxy/drivers/nginx.ts';
import { buildFileDriverScript, type FileSpec } from '../../../../src/lib/proxy/file-driver.ts';

const HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';
const MAP_BLOCKS = [
  'map $http_upgrade $bellhop_connection_upgrade {',
  '    default upgrade;',
  "    ''      '';",
  '}',
  '',
  'map $http_host $bellhop_http_host {',
  '    default $http_host;',
  "    ''      $host;",
  '}',
].join('\n');

// The file's fixed shape (contract "File skeleton"), present even with no
// routes at all -- render's shape never depends on the inventory.
const SKELETON = `${HEADER}\n\n${MAP_BLOCKS}`;

function inv(overrides: Partial<Inventory> = {}): Inventory {
  return {
    domain: 'example.com',
    hosts: [{ name: 'pve1', ssh_target: '192.0.2.1', ssh_user: 'root', proxy: true }],
    guests: [],
    ...overrides,
  };
}

// Builds the same content sync-proxy would preview/write: buildRoutes/
// buildProxyContext have already done the derivation by the time render
// runs, exactly as fileDriver's plan() calls it.
function configOf(inventory: Inventory): string {
  return render(buildRoutes(inventory), buildProxyContext(inventory), '/etc/nginx/conf.d/bellhop.conf')[0].content;
}

// --- (a) skeleton, even with zero routes ------------------------------------

test('render: no routes -> the header comment plus both map blocks only', () => {
  assert.equal(configOf(inv()), SKELETON);
});

// --- (b) one ungated route with two subdomains ------------------------------

test('render: one ungated route with two subdomains -> full server block, canonical hostname first, quoted cert paths, and proxy lines', () => {
  const inventory = inv({
    guests: [
      { name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.10', port: 8080, subdomains: ['app', 'alias'] },
    ],
  });
  const expected = [
    SKELETON,
    '',
    'server {',
    '    listen 443 ssl;',
    '    listen [::]:443 ssl;',
    '    server_name app.example.com alias.example.com;',
    '',
    '    ssl_certificate "/etc/letsencrypt/live/example.com/fullchain.pem";',
    '    ssl_certificate_key "/etc/letsencrypt/live/example.com/privkey.pem";',
    '',
    '    client_max_body_size 0;',
    '    proxy_buffering off;',
    '',
    '    location / {',
    '        proxy_pass http://192.0.2.10:8080;',
    '        proxy_http_version 1.1;',
    '        proxy_set_header Host $bellhop_http_host;',
    '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
    '        proxy_set_header X-Forwarded-Proto $scheme;',
    '        proxy_set_header X-Forwarded-Host $bellhop_http_host;',
    '        proxy_set_header X-Forwarded-Port 443;',
    '        proxy_set_header Upgrade $http_upgrade;',
    '        proxy_set_header Connection $bellhop_connection_upgrade;',
    '    }',
    '}',
  ].join('\n');
  assert.equal(configOf(inventory), expected);
});

// --- (c) insecureBackendTls: true -------------------------------------------

test('render: insecureBackendTls -> https upstream with proxy_ssl_verify off, no CA bundle line', () => {
  const inventory = inv({
    guests: [
      {
        name: 'app-lxc',
        type: 'lxc',
        vmid: 100,
        host: 'pve1',
        ip: '192.0.2.11',
        port: 8443,
        subdomains: ['app'],
        insecureBackendTls: true,
      },
    ],
  });
  const content = configOf(inventory);
  assert.match(content, /proxy_pass https:\/\/192\.0\.2\.11:8443;/);
  assert.match(content, /proxy_ssl_verify off;/);
  assert.doesNotMatch(content, /proxy_ssl_verify on;/);
  assert.doesNotMatch(content, /proxy_ssl_trusted_certificate/);
});

// --- (d) port 443 without insecureBackendTls --------------------------------

test('render: port 443 without insecureBackendTls -> https upstream with proxy_ssl_verify on and the trusted CA bundle', () => {
  const inventory = inv({
    guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.12', port: 443, subdomains: ['app'] }],
  });
  const content = configOf(inventory);
  assert.match(content, /proxy_pass https:\/\/192\.0\.2\.12:443;/);
  assert.match(content, /proxy_ssl_verify on;/);
  assert.match(content, /proxy_ssl_trusted_certificate \/etc\/ssl\/certs\/ca-certificates\.crt;/);
  assert.doesNotMatch(content, /proxy_ssl_verify off;/);
});

// --- (e) authMode: 'oidc' renders identically to ungated --------------------

test("render: an authMode 'oidc' gated route renders identically to an ungated route (no auth_request, no outpost location)", () => {
  const ungated = configOf(
    inv({ guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.13', port: 80, subdomains: ['app'] }] })
  );
  const oidc = configOf(
    inv({
      guests: [
        {
          name: 'app-lxc',
          type: 'lxc',
          vmid: 100,
          host: 'pve1',
          ip: '192.0.2.13',
          port: 80,
          subdomains: ['app'],
          authGroup: 'bellhop-users',
          authMode: 'oidc',
        },
      ],
    })
  );
  assert.equal(oidc, ungated);
  assert.doesNotMatch(oidc, /auth_request/);
  assert.doesNotMatch(oidc, /outpost\.goauthentik\.io/);
});

// --- (f) two routes, one blank line between server blocks -------------------

test('render: two routes produce two server blocks separated by exactly one blank line', () => {
  const inventory = inv({
    guests: [
      { name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.14', port: 80, subdomains: ['app'] },
      { name: 'media-lxc', type: 'lxc', vmid: 101, host: 'pve1', ip: '192.0.2.15', port: 8096, subdomains: ['media'] },
    ],
  });
  const content = configOf(inventory);
  assert.match(content, /\}\n\nserver \{/, 'exactly one blank line separates the two server blocks');
  assert.equal((content.match(/^server \{/gm) ?? []).length, 2);
});

// --- (g) the returned FileSpec ------------------------------------------------

test('render returns exactly one owned FileSpec at configPath', () => {
  const inventory = inv({ guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.16', subdomains: ['app'] }] });
  const files = render(buildRoutes(inventory), buildProxyContext(inventory), '/etc/nginx/conf.d/bellhop.conf');
  assert.equal(files.length, 1);
  assert.equal(files[0].path, '/etc/nginx/conf.d/bellhop.conf');
  assert.equal(files[0].mode, 'owned');
});

// --- (h) driver metadata -----------------------------------------------------

test('nginxDriver declares its id, default config path, and capabilities', () => {
  assert.equal(nginxDriver.id, 'nginx');
  assert.equal(nginxDriver.defaultConfigPath, '/etc/nginx/conf.d/bellhop.conf');
  assert.deepEqual(nginxDriver.capabilities, { authModes: ['forward', 'oidc'], acmeDns01ViaCloudflare: false });
});

// --- User Story 2: forward-gated routes -------------------------------------

// buildProxyContext resolves ctx.outpost from an authentik:true entry's own
// ip plus authentikConfig().outpostPort (AUTHENTIK_OUTPOST_PORT) -- pinned
// here (and restored after) rather than left to whatever the developer's
// shell happens to have set, same convention as
// test/lib/proxy/drivers/caddy.test.ts.
const ORIGINAL_OUTPOST_PORT = process.env.AUTHENTIK_OUTPOST_PORT;

function withPinnedOutpostPort(fn: () => void): void {
  process.env.AUTHENTIK_OUTPOST_PORT = '9000';
  try {
    fn();
  } finally {
    if (ORIGINAL_OUTPOST_PORT === undefined) delete process.env.AUTHENTIK_OUTPOST_PORT;
    else process.env.AUTHENTIK_OUTPOST_PORT = ORIGINAL_OUTPOST_PORT;
  }
}

// One authentik:true entry (ip 192.0.2.20; with AUTHENTIK_OUTPOST_PORT
// pinned to '9000' above, ctx.outpost becomes 192.0.2.20:9000) plus one
// forward-gated guest (ip 192.0.2.30, port 8080, subdomain 'app') built from
// the given overrides -- e.g. unauthenticatedPaths.
function gatedInventory(guestOverrides: Record<string, unknown> = {}): Inventory {
  return inv({
    guests: [
      { name: 'auth-lxc', type: 'lxc', vmid: 130, host: 'pve1', ip: '192.0.2.20', authentik: true },
      {
        name: 'app-lxc',
        type: 'lxc',
        vmid: 120,
        host: 'pve1',
        ip: '192.0.2.30',
        port: 8080,
        subdomains: ['app'],
        authGroup: 'bellhop-users',
        ...guestOverrides,
      },
    ],
  });
}

// app-lxc's own proxy lines (contract "Proxy lines"), reused verbatim by
// `location /` and every exempt location.
const APP_PROXY_LINES = [
  '        proxy_pass http://192.0.2.30:8080;',
  '        proxy_http_version 1.1;',
  '        proxy_set_header Host $bellhop_http_host;',
  '        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;',
  '        proxy_set_header X-Forwarded-Proto $scheme;',
  '        proxy_set_header X-Forwarded-Host $bellhop_http_host;',
  '        proxy_set_header X-Forwarded-Port 443;',
  '        proxy_set_header Upgrade $http_upgrade;',
  '        proxy_set_header Connection $bellhop_connection_upgrade;',
];

// Authentik's identity-forwarding lines appended to `location /` (contract
// "Forward-gated route" #2): five identity headers (username, groups,
// email, name, uid), no entitlements.
const FORWARD_AUTH_LINES = [
  '        auth_request /outpost.goauthentik.io/auth/nginx;',
  '        error_page 401 = @goauthentik_proxy_signin;',
  '        auth_request_set $bellhop_auth_cookie $upstream_http_set_cookie;',
  '        add_header Set-Cookie $bellhop_auth_cookie;',
  '        auth_request_set $bellhop_authentik_username $upstream_http_x_authentik_username;',
  '        auth_request_set $bellhop_authentik_groups $upstream_http_x_authentik_groups;',
  '        auth_request_set $bellhop_authentik_email $upstream_http_x_authentik_email;',
  '        auth_request_set $bellhop_authentik_name $upstream_http_x_authentik_name;',
  '        auth_request_set $bellhop_authentik_uid $upstream_http_x_authentik_uid;',
  '        proxy_set_header X-authentik-username $bellhop_authentik_username;',
  '        proxy_set_header X-authentik-groups $bellhop_authentik_groups;',
  '        proxy_set_header X-authentik-email $bellhop_authentik_email;',
  '        proxy_set_header X-authentik-name $bellhop_authentik_name;',
  '        proxy_set_header X-authentik-uid $bellhop_authentik_uid;',
];

// The outpost passthrough and sign-in named locations (contract
// "Forward-gated route" #4), with ctx.outpost = 192.0.2.20:9000. Always
// present on a forward-gated route.
const OUTPOST_LOCATIONS = [
  '',
  '    location /outpost.goauthentik.io {',
  '        proxy_pass http://192.0.2.20:9000/outpost.goauthentik.io;',
  '        proxy_set_header Host $bellhop_http_host;',
  '        proxy_set_header X-Original-URL $scheme://$bellhop_http_host$request_uri;',
  '        add_header Set-Cookie $bellhop_auth_cookie;',
  '        auth_request_set $bellhop_auth_cookie $upstream_http_set_cookie;',
  '        proxy_pass_request_body off;',
  '        proxy_set_header Content-Length "";',
  '    }',
  '',
  '    location @goauthentik_proxy_signin {',
  '        internal;',
  '        add_header Set-Cookie $bellhop_auth_cookie;',
  '        return 302 /outpost.goauthentik.io/start?rd=$scheme://$bellhop_http_host$request_uri;',
  '    }',
];

// The head of app-lxc's server block, through the (gated-only) buffer lines
// and the blank line before `location /`.
function gatedServerHead(): string[] {
  return [
    'server {',
    '    listen 443 ssl;',
    '    listen [::]:443 ssl;',
    '    server_name app.example.com;',
    '',
    '    ssl_certificate "/etc/letsencrypt/live/example.com/fullchain.pem";',
    '    ssl_certificate_key "/etc/letsencrypt/live/example.com/privkey.pem";',
    '',
    '    client_max_body_size 0;',
    '    proxy_buffering off;',
    '    proxy_buffers 8 16k;',
    '    proxy_buffer_size 32k;',
    '',
  ];
}

// --- (a) gated route, no exempt paths ---------------------------------------

test('render: forward-gated route with no exempt paths -> buffer lines, full auth_request block in location /, outpost and sign-in locations', () => {
  withPinnedOutpostPort(() => {
    const content = configOf(gatedInventory());
    const expected = [
      SKELETON,
      '',
      ...gatedServerHead(),
      '    location / {',
      ...APP_PROXY_LINES,
      ...FORWARD_AUTH_LINES,
      '    }',
      ...OUTPOST_LOCATIONS,
      '}',
    ].join('\n');
    assert.equal(content, expected);
  });
});

// --- (b) exempt /health and /api/* -------------------------------------------

test('render: exempt /health and /api/* -> location = "/health" and location ^~ "/api/" after location /, each with only proxy lines, in stored order', () => {
  withPinnedOutpostPort(() => {
    const content = configOf(gatedInventory({ unauthenticatedPaths: ['/health', '/api/*'] }));
    const expected = [
      SKELETON,
      '',
      ...gatedServerHead(),
      '    location / {',
      ...APP_PROXY_LINES,
      ...FORWARD_AUTH_LINES,
      '    }',
      '',
      '    location = "/health" {',
      ...APP_PROXY_LINES,
      '    }',
      '',
      '    location ^~ "/api/" {',
      ...APP_PROXY_LINES,
      '    }',
      ...OUTPOST_LOCATIONS,
      '}',
    ].join('\n');
    assert.equal(content, expected);
  });
});

// --- (c) duplicate exempt entries -> one location each ----------------------

test('render: duplicate exempt entries produce one location each, in first-seen order', () => {
  withPinnedOutpostPort(() => {
    const content = configOf(gatedInventory({ unauthenticatedPaths: ['/health', '/health', '/api/*', '/api/*'] }));
    const expected = [
      SKELETON,
      '',
      ...gatedServerHead(),
      '    location / {',
      ...APP_PROXY_LINES,
      ...FORWARD_AUTH_LINES,
      '    }',
      '',
      '    location = "/health" {',
      ...APP_PROXY_LINES,
      '    }',
      '',
      '    location ^~ "/api/" {',
      ...APP_PROXY_LINES,
      '    }',
      ...OUTPOST_LOCATIONS,
      '}',
    ].join('\n');
    assert.equal(content, expected);
  });
});

// --- (d) exempt /* -----------------------------------------------------------

test('render: exempt /* -> location / has proxy lines only (no auth lines), no location ^~ "/", outpost and sign-in locations still present', () => {
  withPinnedOutpostPort(() => {
    const content = configOf(gatedInventory({ unauthenticatedPaths: ['/*'] }));
    const expected = [
      SKELETON,
      '',
      ...gatedServerHead(),
      '    location / {',
      ...APP_PROXY_LINES,
      '    }',
      ...OUTPOST_LOCATIONS,
      '}',
    ].join('\n');
    assert.equal(content, expected);
    assert.doesNotMatch(content, /location \^~ "\/"/);
  });
});

// --- (e) an exempt path containing a quote and a space ----------------------

test('render: an exempt path containing a quote and a space is emitted quoted and escaped', () => {
  withPinnedOutpostPort(() => {
    const content = configOf(gatedInventory({ unauthenticatedPaths: ['/say "hi'] }));
    const expected = [
      SKELETON,
      '',
      ...gatedServerHead(),
      '    location / {',
      ...APP_PROXY_LINES,
      ...FORWARD_AUTH_LINES,
      '    }',
      '',
      `    location = "/say \\"hi" {`,
      ...APP_PROXY_LINES,
      '    }',
      ...OUTPOST_LOCATIONS,
      '}',
    ].join('\n');
    assert.equal(content, expected);
  });
});

// --- (f) no authentik:true entry -> buildRoutes's own error, unhandled ------

test('render: a forward-gated inventory with no authentik:true entry still throws the existing missing-authentik error from buildRoutes', () => {
  const inventory = inv({
    guests: [
      {
        name: 'app-lxc',
        type: 'lxc',
        vmid: 120,
        host: 'pve1',
        ip: '192.0.2.30',
        port: 8080,
        subdomains: ['app'],
        authGroup: 'bellhop-users',
      },
    ],
  });
  assert.throws(
    () => configOf(inventory),
    /^Error: Entry 'app-lxc' has an 'authGroup' set but no inventory entry has 'authentik: true' with an ip set$/
  );
});

// --- executed-script test (research R9): the 'owned' delivery path ---------

function shAvailable(): boolean {
  const result = spawnSync('sh', ['-c', 'exit 0']);
  return result.error === undefined || result.error === null;
}

test('nginxDriver apply script, executed: a failed "nginx -t" restores an existing file byte for byte, exits non-zero, and never reloads', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }

  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-stubs-'));
  const posix = (p: string) => p.replace(/\\/g, '/');
  const confPath = posix(join(tmpDir, 'bellhop.conf'));
  const systemctlLogPath = posix(join(tmpDir, 'systemctl.log'));

  const originalContent = 'server {\n    server_name old.example.com;\n}';
  writeFileSync(confPath, originalContent);

  const newContent = 'server {\n    server_name new.example.com;\n}';
  const files: FileSpec[] = [{ path: confPath, content: newContent, mode: 'owned' }];
  const script = buildFileDriverScript(files, 'nginx -t', 'systemctl reload nginx');
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  const nginxFailPath = join(stubDir, 'nginx');
  writeFileSync(nginxFailPath, '#!/bin/sh\nexit 1\n');
  chmodSync(nginxFailPath, 0o755);
  const systemctlPath = join(stubDir, 'systemctl');
  writeFileSync(systemctlPath, `#!/bin/sh\necho "$@" >> '${systemctlLogPath}'\n`);
  chmodSync(systemctlPath, 0o755);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}` };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.equal(result.status, 1, `expected exit 1, got ${result.status}, stderr: ${result.stderr}`);
  assert.equal(readFileSync(confPath, 'utf8'), originalContent, 'the original file must be restored byte for byte');
  assert.ok(!existsSync(systemctlLogPath), 'systemctl must not have been called');
});

test('nginxDriver apply script, executed: a failed "nginx -t" removes a file that did not exist before, and never reloads', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }

  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-noexist-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-noexist-stubs-'));
  const posix = (p: string) => p.replace(/\\/g, '/');
  const confPath = posix(join(tmpDir, 'bellhop.conf'));
  const systemctlLogPath = posix(join(tmpDir, 'systemctl.log'));

  const newContent = 'server {\n    server_name new.example.com;\n}';
  const files: FileSpec[] = [{ path: confPath, content: newContent, mode: 'owned' }];
  const script = buildFileDriverScript(files, 'nginx -t', 'systemctl reload nginx');
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  const nginxFailPath = join(stubDir, 'nginx');
  writeFileSync(nginxFailPath, '#!/bin/sh\nexit 1\n');
  chmodSync(nginxFailPath, 0o755);
  const systemctlPath = join(stubDir, 'systemctl');
  writeFileSync(systemctlPath, `#!/bin/sh\necho "$@" >> '${systemctlLogPath}'\n`);
  chmodSync(systemctlPath, 0o755);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}` };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.equal(result.status, 1, `expected exit 1, got ${result.status}, stderr: ${result.stderr}`);
  assert.ok(!existsSync(confPath), 'a file that did not exist before must be removed on restore, not left behind');
  assert.ok(!existsSync(systemctlLogPath), 'systemctl must not have been called');
});

test('nginxDriver apply script, executed: a successful "nginx -t" writes the new content once and reloads nginx once', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }

  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-ok-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-nginx-driver-ok-stubs-'));
  const posix = (p: string) => p.replace(/\\/g, '/');
  const confPath = posix(join(tmpDir, 'bellhop.conf'));
  const systemctlLogPath = posix(join(tmpDir, 'systemctl.log'));

  const originalContent = 'server {\n    server_name old.example.com;\n}';
  writeFileSync(confPath, originalContent);

  const newContent = 'server {\n    server_name new.example.com;\n}';
  const files: FileSpec[] = [{ path: confPath, content: newContent, mode: 'owned' }];
  const script = buildFileDriverScript(files, 'nginx -t', 'systemctl reload nginx');
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  const nginxOkPath = join(stubDir, 'nginx');
  writeFileSync(nginxOkPath, '#!/bin/sh\nexit 0\n');
  chmodSync(nginxOkPath, 0o755);
  const systemctlPath = join(stubDir, 'systemctl');
  writeFileSync(systemctlPath, `#!/bin/sh\necho "$@" >> '${systemctlLogPath}'\n`);
  chmodSync(systemctlPath, 0o755);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}` };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.equal(result.status, 0, `expected exit 0, got ${result.status}, stderr: ${result.stderr}`);
  // The heredoc buildFileDriverScript uses to write an 'owned' file always
  // ends with a newline (same as every other `cat <<'TAG'` in this script),
  // same convention the file-driver tests use for a managed-section file.
  assert.equal(readFileSync(confPath, 'utf8'), `${newContent}\n`, 'the new content must be written whole');
  assert.equal(readFileSync(systemctlLogPath, 'utf8').trim(), 'reload nginx', 'systemctl reload nginx must have run exactly once');
});
