// User Story 1 (issue #35): render tests pinned against
// specs/015-traefik-proxy-driver/contracts/traefik-driver.md's "Rendered
// file: example" -- the *wiki* (ungated) entry's shape only. Forward-auth/
// outpost/exempt objects are User Story 2 and are exercised in a later test
// file, not here.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { parse } from 'yaml';
import { buildRoutes, buildProxyContext, type ProxyContext, type ProxyRoute } from '../../../../src/lib/proxy/routes.ts';
import { encodeHostname, generationMarkerName, render, routeName, routerNames, ruleValue } from '../../../../src/lib/proxy/drivers/traefik.ts';
import type { Inventory } from '../../../../src/lib/inventory.ts';

const HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';
const CONFIG_PATH = '/etc/traefik/dynamic/bellhop.yml';

function ctx(overrides: Partial<ProxyContext> = {}): ProxyContext {
  return {
    externalPort: 443,
    tls: {
      certificatePath: '/etc/letsencrypt/live/example.com/fullchain.pem',
      keyPath: '/etc/letsencrypt/live/example.com/privkey.pem',
    },
    certResolver: 'cloudflare',
    ...overrides,
  };
}

function route(overrides: Partial<ProxyRoute> & { owner: ProxyRoute['owner'] }): ProxyRoute {
  return {
    hostnames: [`${overrides.owner.name}.example.com`],
    backend: { ip: '192.0.2.30', port: 80, insecureTls: false },
    auth: { mode: 'ungated' },
    ...overrides,
  };
}

function renderOne(r: ProxyRoute, c: ProxyContext = ctx()): string {
  return render([r], c, CONFIG_PATH)[0].content;
}

// The forwarded-port middleware body, present in every rendered file
// regardless of routes (research.md R7).
const FORWARDED_PORT_MIDDLEWARE = ['    bellhop-forwarded-port:', '      headers:', '        customRequestHeaders:', '          X-Forwarded-Port: "443"'];

function sha256First12(content: string): string {
  return createHash('sha256').update(content).digest('hex').slice(0, 12);
}

// --- encodeHostname / ruleValue / name helpers -------------------------------

test('encodeHostname: lowercases, doubles "-", then turns "." into "-" -- injective, so two different hostnames never collide', () => {
  assert.equal(encodeHostname('Wiki.Example.com'), 'wiki-example-com');
  assert.equal(encodeHostname('a.b-c.example.com'), 'a-b--c-example-com');
  assert.equal(encodeHostname('a-b.c.example.com'), 'a--b-c-example-com');
  assert.notEqual(encodeHostname('a.b-c.example.com'), encodeHostname('a-b.c.example.com'));
});

test('routeName: bellhop-route-<encoded canonical hostname>', () => {
  assert.equal(routeName('wiki.example.com'), 'bellhop-route-wiki-example-com');
});

test('ruleValue: no backtick -> backtick-quoted', () => {
  assert.equal(ruleValue('wiki.example.com'), '`wiki.example.com`');
  assert.equal(ruleValue('/health'), '`/health`');
});

test('ruleValue: a value containing a backtick -> JSON.stringify (double-quoted Go-style escaping)', () => {
  const value = '/a`b"c\\d';
  assert.equal(ruleValue(value), JSON.stringify(value));
  assert.equal(ruleValue(value), '"/a`b\\"c\\\\d"');
});

// --- render: the contract's *wiki* entry (ungated, two hostnames) -----------

test('render: the contract example\'s wiki entry -- rule order, entry point, service, middlewares, tls.certResolver, and http service URL', () => {
  const wiki = route({
    owner: { type: 'guest', name: 'wiki' },
    hostnames: ['wiki.example.com', 'docs.example.com'],
    backend: { ip: '192.0.2.20', port: 8080, insecureTls: false },
  });

  // The body without the marker, built the same way render() computes its
  // own hash input -- the test recomputes the hash independently (via
  // node:crypto directly, not by importing render()'s internals) so this is
  // a real pin on the hashing behavior, not a tautology.
  const bodyWithoutMarker = [
    'http:',
    '  routers:',
    '    bellhop-route-wiki-example-com:',
    '      rule: Host(`wiki.example.com`) || Host(`docs.example.com`)',
    '      entryPoints:',
    '        - websecure',
    '      service: bellhop-route-wiki-example-com',
    '      middlewares:',
    '        - bellhop-forwarded-port',
    '      tls:',
    '        certResolver: cloudflare',
    '  services:',
    '    bellhop-route-wiki-example-com:',
    '      loadBalancer:',
    '        servers:',
    '          - url: http://192.0.2.20:8080',
    '  middlewares:',
    ...FORWARDED_PORT_MIDDLEWARE,
    '',
  ].join('\n');
  const contentWithoutMarker = `${HEADER}\n${bodyWithoutMarker}`;
  const hash = sha256First12(contentWithoutMarker);

  const expected = [
    HEADER,
    'http:',
    '  routers:',
    '    bellhop-route-wiki-example-com:',
    '      rule: Host(`wiki.example.com`) || Host(`docs.example.com`)',
    '      entryPoints:',
    '        - websecure',
    '      service: bellhop-route-wiki-example-com',
    '      middlewares:',
    '        - bellhop-forwarded-port',
    '      tls:',
    '        certResolver: cloudflare',
    '  services:',
    '    bellhop-route-wiki-example-com:',
    '      loadBalancer:',
    '        servers:',
    '          - url: http://192.0.2.20:8080',
    '  middlewares:',
    ...FORWARDED_PORT_MIDDLEWARE,
    `    bellhop-generation-${hash}:`,
    '      headers:',
    '        customRequestHeaders:',
    `          X-Bellhop-Generation: "${hash}"`,
    '',
  ].join('\n');

  assert.equal(renderOne(wiki), expected);
});

test('render: entry point is always [websecure], and middlewares lists bellhop-forwarded-port only for an ungated route', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' } }));
  const doc = parse(content) as { http: { routers: Record<string, { entryPoints: string[]; middlewares: string[] }> } };
  const router = doc.http.routers['bellhop-route-app-example-com'];
  assert.deepEqual(router.entryPoints, ['websecure']);
  assert.deepEqual(router.middlewares, ['bellhop-forwarded-port']);
});

// --- render: backend scheme (research.md R8) --------------------------------

test('render: a plain port (not 443, not insecureTls) -> http:// service URL, no serversTransport, no serversTransports block', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.10', port: 8080, insecureTls: false } }));
  const doc = parse(content) as { http: { services: Record<string, { loadBalancer: { servers: { url: string }[]; serversTransport?: string } }>; serversTransports?: unknown } };
  const service = doc.http.services['bellhop-route-app-example-com'];
  assert.equal(service.loadBalancer.servers[0].url, 'http://192.0.2.10:8080');
  assert.equal(service.loadBalancer.serversTransport, undefined);
  assert.equal(doc.http.serversTransports, undefined);
});

test('render: a port-443 backend -> https:// service URL, but no serversTransport (the default transport already verifies)', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.10', port: 443, insecureTls: false } }));
  const doc = parse(content) as { http: { services: Record<string, { loadBalancer: { servers: { url: string }[]; serversTransport?: string } }>; serversTransports?: unknown } };
  const service = doc.http.services['bellhop-route-app-example-com'];
  assert.equal(service.loadBalancer.servers[0].url, 'https://192.0.2.10:443');
  assert.equal(service.loadBalancer.serversTransport, undefined);
  assert.equal(doc.http.serversTransports, undefined);
});

test('render: insecureTls -> https:// service URL, serversTransport bellhop-insecure-backend-tls, and the shared serversTransports.insecureSkipVerify block', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.10', port: 8443, insecureTls: true } }));
  const doc = parse(content) as {
    http: {
      services: Record<string, { loadBalancer: { servers: { url: string }[]; serversTransport?: string } }>;
      serversTransports?: Record<string, { insecureSkipVerify: boolean }>;
    };
  };
  const service = doc.http.services['bellhop-route-app-example-com'];
  assert.equal(service.loadBalancer.servers[0].url, 'https://192.0.2.10:8443');
  assert.equal(service.loadBalancer.serversTransport, 'bellhop-insecure-backend-tls');
  assert.deepEqual(doc.http.serversTransports, { 'bellhop-insecure-backend-tls': { insecureSkipVerify: true } });
});

// --- render: OIDC renders identically to ungated ----------------------------

test('render: an OIDC route renders identically to the same route ungated -- no auth objects exist yet (User Story 2)', () => {
  const ungated = route({ owner: { type: 'externalSite', name: 'nas' }, auth: { mode: 'ungated' } });
  const oidc = route({ owner: { type: 'externalSite', name: 'nas' }, auth: { mode: 'oidc' } });
  assert.equal(renderOne(ungated), renderOne(oidc));
});

// --- render: zero routes -----------------------------------------------------

test('render: zero routes -> header plus http.middlewares holding only bellhop-forwarded-port and the marker -- no routers/services/serversTransports', () => {
  const content = render([], ctx(), CONFIG_PATH)[0].content;
  assert.equal(content.split('\n')[0], HEADER);
  const doc = parse(content) as {
    http: { routers?: unknown; services?: unknown; serversTransports?: unknown; middlewares: Record<string, unknown> };
  };
  assert.equal(doc.http.routers, undefined);
  assert.equal(doc.http.services, undefined);
  assert.equal(doc.http.serversTransports, undefined);
  const names = Object.keys(doc.http.middlewares);
  assert.equal(names.length, 2);
  assert.equal(names[0], 'bellhop-forwarded-port');
  assert.ok(names[1].startsWith('bellhop-generation-'), `expected a generation marker, got '${names[1]}'`);
});

// --- render: FileSpec shape --------------------------------------------------

test('render: returns one owned, atomic FileSpec at configPath, owned by its header', () => {
  const files = render([route({ owner: { type: 'guest', name: 'app' } })], ctx(), CONFIG_PATH);
  assert.equal(files.length, 1);
  assert.equal(files[0].path, CONFIG_PATH);
  assert.equal(files[0].mode, 'owned');
  assert.equal(files[0].ownedHeader, HEADER);
  assert.equal(files[0].atomic, true);
});

// --- generation marker: stability and change detection (research.md R3) ----

test('generationMarkerName: stable across two renders of the same routes, and different when a route changes', () => {
  const routes = [route({ owner: { type: 'guest', name: 'app' } })];
  const first = render(routes, ctx(), CONFIG_PATH)[0].content;
  const second = render(routes, ctx(), CONFIG_PATH)[0].content;
  assert.equal(first, second, 'two renders of the same input must be byte-identical');
  assert.equal(generationMarkerName(first), generationMarkerName(second));

  const changed = [route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.99', port: 80, insecureTls: false } })];
  const third = render(changed, ctx(), CONFIG_PATH)[0].content;
  assert.notEqual(generationMarkerName(first), generationMarkerName(third), 'a changed route must change the marker hash');
});

test('routerNames: every router name, in render order', () => {
  const routes = [route({ owner: { type: 'guest', name: 'zeta' } }), route({ owner: { type: 'guest', name: 'alpha' } })];
  const content = render(routes, ctx(), CONFIG_PATH)[0].content;
  assert.deepEqual(routerNames(content), ['bellhop-route-zeta-example-com', 'bellhop-route-alpha-example-com']);
});

test('routerNames: empty for zero routes', () => {
  const content = render([], ctx(), CONFIG_PATH)[0].content;
  assert.deepEqual(routerNames(content), []);
});

// --- render: driven through buildRoutes/buildProxyContext, like sync-proxy --

function inv(overrides: Partial<Inventory> = {}): Inventory {
  return {
    domain: 'example.com',
    hosts: [{ name: 'pve1', ssh_target: '192.0.2.1', ssh_user: 'root', proxy: true }],
    guests: [],
    ...overrides,
  };
}

test('render via buildRoutes/buildProxyContext: proxyCertResolver flows into every router\'s tls.certResolver', () => {
  const inventory = inv({
    proxyCertResolver: 'my-resolver',
    guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.10', port: 8080, subdomains: ['app'] }],
  });
  const content = render(buildRoutes(inventory), buildProxyContext(inventory), CONFIG_PATH)[0].content;
  const doc = parse(content) as { http: { routers: Record<string, { tls: { certResolver: string } }> } };
  assert.equal(doc.http.routers['bellhop-route-app-example-com'].tls.certResolver, 'my-resolver');
});

test('render via buildRoutes/buildProxyContext: an unset proxyCertResolver falls back to cloudflare', () => {
  const inventory = inv({
    guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.10', port: 8080, subdomains: ['app'] }],
  });
  const content = render(buildRoutes(inventory), buildProxyContext(inventory), CONFIG_PATH)[0].content;
  const doc = parse(content) as { http: { routers: Record<string, { tls: { certResolver: string } }> } };
  assert.equal(doc.http.routers['bellhop-route-app-example-com'].tls.certResolver, 'cloudflare');
});
