// User Story 1 (issue #35): render tests pinned against
// specs/015-traefik-proxy-driver/contracts/traefik-driver.md's "Rendered
// file: example" -- the *wiki* (ungated) entry's shape only. Forward-auth/
// outpost/exempt objects are User Story 2 and are exercised in a later test
// file, not here.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { parse, stringify } from 'yaml';
import { buildRoutes, buildProxyContext, parsePathPattern, type ProxyContext, type ProxyRoute } from '../../../../src/lib/proxy/routes.ts';
import { encodeHostname, generationMarkerName, render, routeName, routerNames, ruleValue } from '../../../../src/lib/proxy/drivers/traefik.ts';
import type { Inventory } from '../../../../src/lib/inventory.ts';

const HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';
const CONFIG_PATH = '/etc/traefik/dynamic/bellhop.yml';

function ctx(overrides: Partial<ProxyContext> = {}): ProxyContext {
  return {
    externalPort: 443,
    tls: {
      certificatePath: '/etc/letsencrypt/live/example.com/fullchain.pem',
      keyPath: '/etc/letsencrypt/live/example.com/privkey.pem',
    },
    certResolver: 'cloudflare',
    ...overrides,
  };
}

function route(overrides: Partial<ProxyRoute> & { owner: ProxyRoute['owner'] }): ProxyRoute {
  return {
    hostnames: [`${overrides.owner.name}.example.com`],
    backend: { ip: '192.0.2.30', port: 80, insecureTls: false },
    auth: { mode: 'ungated' },
    ...overrides,
  };
}

function renderOne(r: ProxyRoute, c: ProxyContext = ctx()): string {
  return render([r], c, CONFIG_PATH)[0].content;
}

// The forwarded-port middleware body, present in every rendered file
// regardless of routes (research.md R7).
const FORWARDED_PORT_MIDDLEWARE = ['    bellhop-forwarded-port:', '      headers:', '        customRequestHeaders:', '          X-Forwarded-Port: "443"'];

function sha256First12(content: string): string {
  return createHash('sha256').update(content).digest('hex').slice(0, 12);
}

// --- encodeHostname / ruleValue / name helpers -------------------------------

test('encodeHostname: lowercases, doubles "-", then turns "." into "-" -- injective, so two different hostnames never collide', () => {
  assert.equal(encodeHostname('Wiki.Example.com'), 'wiki-example-com');
  assert.equal(encodeHostname('a.b-c.example.com'), 'a-b--c-example-com');
  assert.equal(encodeHostname('a-b.c.example.com'), 'a--b-c-example-com');
  assert.notEqual(encodeHostname('a.b-c.example.com'), encodeHostname('a-b.c.example.com'));
});

test('routeName: bellhop-route-<encoded canonical hostname>', () => {
  assert.equal(routeName('wiki.example.com'), 'bellhop-route-wiki-example-com');
});

test('ruleValue: no backtick -> backtick-quoted', () => {
  assert.equal(ruleValue('wiki.example.com'), '`wiki.example.com`');
  assert.equal(ruleValue('/health'), '`/health`');
});

test('ruleValue: a value containing a backtick -> JSON.stringify (double-quoted Go-style escaping)', () => {
  const value = '/a`b"c\\d';
  assert.equal(ruleValue(value), JSON.stringify(value));
  assert.equal(ruleValue(value), '"/a`b\\"c\\\\d"');
});

// --- render: the contract's *wiki* entry (ungated, two hostnames) -----------

test('render: the contract example\'s wiki entry -- rule order, entry point, service, middlewares, tls.certResolver, and http service URL', () => {
  const wiki = route({
    owner: { type: 'guest', name: 'wiki' },
    hostnames: ['wiki.example.com', 'docs.example.com'],
    backend: { ip: '192.0.2.20', port: 8080, insecureTls: false },
  });

  // The body without the marker, built the same way render() computes its
  // own hash input -- the test recomputes the hash independently (via
  // node:crypto directly, not by importing render()'s internals) so this is
  // a real pin on the hashing behavior, not a tautology.
  const bodyWithoutMarker = [
    'http:',
    '  routers:',
    '    bellhop-route-wiki-example-com:',
    '      rule: Host(`wiki.example.com`) || Host(`docs.example.com`)',
    '      entryPoints:',
    '        - websecure',
    '      service: bellhop-route-wiki-example-com',
    '      middlewares:',
    '        - bellhop-forwarded-port',
    '      tls:',
    '        certResolver: cloudflare',
    '  services:',
    '    bellhop-route-wiki-example-com:',
    '      loadBalancer:',
    '        servers:',
    '          - url: http://192.0.2.20:8080',
    '  middlewares:',
    ...FORWARDED_PORT_MIDDLEWARE,
    '',
  ].join('\n');
  const contentWithoutMarker = `${HEADER}\n${bodyWithoutMarker}`;
  const hash = sha256First12(contentWithoutMarker);

  const expected = [
    HEADER,
    'http:',
    '  routers:',
    '    bellhop-route-wiki-example-com:',
    '      rule: Host(`wiki.example.com`) || Host(`docs.example.com`)',
    '      entryPoints:',
    '        - websecure',
    '      service: bellhop-route-wiki-example-com',
    '      middlewares:',
    '        - bellhop-forwarded-port',
    '      tls:',
    '        certResolver: cloudflare',
    '  services:',
    '    bellhop-route-wiki-example-com:',
    '      loadBalancer:',
    '        servers:',
    '          - url: http://192.0.2.20:8080',
    '  middlewares:',
    ...FORWARDED_PORT_MIDDLEWARE,
    `    bellhop-generation-${hash}:`,
    '      headers:',
    '        customRequestHeaders:',
    `          X-Bellhop-Generation: "${hash}"`,
    '',
  ].join('\n');

  assert.equal(renderOne(wiki), expected);
});

test('render: entry point is always [websecure], and middlewares lists bellhop-forwarded-port only for an ungated route', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' } }));
  const doc = parse(content) as { http: { routers: Record<string, { entryPoints: string[]; middlewares: string[] }> } };
  const router = doc.http.routers['bellhop-route-app-example-com'];
  assert.deepEqual(router.entryPoints, ['websecure']);
  assert.deepEqual(router.middlewares, ['bellhop-forwarded-port']);
});

// --- render: backend scheme (research.md R8) --------------------------------

test('render: a plain port (not 443, not insecureTls) -> http:// service URL, no serversTransport, no serversTransports block', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.10', port: 8080, insecureTls: false } }));
  const doc = parse(content) as { http: { services: Record<string, { loadBalancer: { servers: { url: string }[]; serversTransport?: string } }>; serversTransports?: unknown } };
  const service = doc.http.services['bellhop-route-app-example-com'];
  assert.equal(service.loadBalancer.servers[0].url, 'http://192.0.2.10:8080');
  assert.equal(service.loadBalancer.serversTransport, undefined);
  assert.equal(doc.http.serversTransports, undefined);
});

test('render: a port-443 backend -> https:// service URL, but no serversTransport (the default transport already verifies)', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.10', port: 443, insecureTls: false } }));
  const doc = parse(content) as { http: { services: Record<string, { loadBalancer: { servers: { url: string }[]; serversTransport?: string } }>; serversTransports?: unknown } };
  const service = doc.http.services['bellhop-route-app-example-com'];
  assert.equal(service.loadBalancer.servers[0].url, 'https://192.0.2.10:443');
  assert.equal(service.loadBalancer.serversTransport, undefined);
  assert.equal(doc.http.serversTransports, undefined);
});

test('render: insecureTls -> https:// service URL, serversTransport bellhop-insecure-backend-tls, and the shared serversTransports.insecureSkipVerify block', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.10', port: 8443, insecureTls: true } }));
  const doc = parse(content) as {
    http: {
      services: Record<string, { loadBalancer: { servers: { url: string }[]; serversTransport?: string } }>;
      serversTransports?: Record<string, { insecureSkipVerify: boolean }>;
    };
  };
  const service = doc.http.services['bellhop-route-app-example-com'];
  assert.equal(service.loadBalancer.servers[0].url, 'https://192.0.2.10:8443');
  assert.equal(service.loadBalancer.serversTransport, 'bellhop-insecure-backend-tls');
  assert.deepEqual(doc.http.serversTransports, { 'bellhop-insecure-backend-tls': { insecureSkipVerify: true } });
});

// --- render: OIDC renders identically to ungated ----------------------------

test('render: an OIDC route renders identically to the same route ungated -- no auth objects exist yet (User Story 2)', () => {
  const ungated = route({ owner: { type: 'externalSite', name: 'nas' }, auth: { mode: 'ungated' } });
  const oidc = route({ owner: { type: 'externalSite', name: 'nas' }, auth: { mode: 'oidc' } });
  assert.equal(renderOne(ungated), renderOne(oidc));
});

// --- render: zero routes -----------------------------------------------------

test('render: zero routes -> header plus http.middlewares holding only bellhop-forwarded-port and the marker -- no routers/services/serversTransports', () => {
  const content = render([], ctx(), CONFIG_PATH)[0].content;
  assert.equal(content.split('\n')[0], HEADER);
  const doc = parse(content) as {
    http: { routers?: unknown; services?: unknown; serversTransports?: unknown; middlewares: Record<string, unknown> };
  };
  assert.equal(doc.http.routers, undefined);
  assert.equal(doc.http.services, undefined);
  assert.equal(doc.http.serversTransports, undefined);
  const names = Object.keys(doc.http.middlewares);
  assert.equal(names.length, 2);
  assert.equal(names[0], 'bellhop-forwarded-port');
  assert.ok(names[1].startsWith('bellhop-generation-'), `expected a generation marker, got '${names[1]}'`);
});

// --- render: FileSpec shape --------------------------------------------------

test('render: returns one owned, atomic FileSpec at configPath, owned by its header', () => {
  const files = render([route({ owner: { type: 'guest', name: 'app' } })], ctx(), CONFIG_PATH);
  assert.equal(files.length, 1);
  assert.equal(files[0].path, CONFIG_PATH);
  assert.equal(files[0].mode, 'owned');
  assert.equal(files[0].ownedHeader, HEADER);
  assert.equal(files[0].atomic, true);
});

// --- generation marker: stability and change detection (research.md R3) ----

test('generationMarkerName: stable across two renders of the same routes, and different when a route changes', () => {
  const routes = [route({ owner: { type: 'guest', name: 'app' } })];
  const first = render(routes, ctx(), CONFIG_PATH)[0].content;
  const second = render(routes, ctx(), CONFIG_PATH)[0].content;
  assert.equal(first, second, 'two renders of the same input must be byte-identical');
  assert.equal(generationMarkerName(first), generationMarkerName(second));

  const changed = [route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.99', port: 80, insecureTls: false } })];
  const third = render(changed, ctx(), CONFIG_PATH)[0].content;
  assert.notEqual(generationMarkerName(first), generationMarkerName(third), 'a changed route must change the marker hash');
});

test('routerNames: every router name, in render order', () => {
  const routes = [route({ owner: { type: 'guest', name: 'zeta' } }), route({ owner: { type: 'guest', name: 'alpha' } })];
  const content = render(routes, ctx(), CONFIG_PATH)[0].content;
  assert.deepEqual(routerNames(content), ['bellhop-route-zeta-example-com', 'bellhop-route-alpha-example-com']);
});

test('routerNames: empty for zero routes', () => {
  const content = render([], ctx(), CONFIG_PATH)[0].content;
  assert.deepEqual(routerNames(content), []);
});

// --- render: driven through buildRoutes/buildProxyContext, like sync-proxy --

function inv(overrides: Partial<Inventory> = {}): Inventory {
  return {
    domain: 'example.com',
    hosts: [{ name: 'pve1', ssh_target: '192.0.2.1', ssh_user: 'root', proxy: true }],
    guests: [],
    ...overrides,
  };
}

test('render via buildRoutes/buildProxyContext: proxyCertResolver flows into every router\'s tls.certResolver', () => {
  const inventory = inv({
    proxyCertResolver: 'my-resolver',
    guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.10', port: 8080, subdomains: ['app'] }],
  });
  const content = render(buildRoutes(inventory), buildProxyContext(inventory), CONFIG_PATH)[0].content;
  const doc = parse(content) as { http: { routers: Record<string, { tls: { certResolver: string } }> } };
  assert.equal(doc.http.routers['bellhop-route-app-example-com'].tls.certResolver, 'my-resolver');
});

test('render via buildRoutes/buildProxyContext: an unset proxyCertResolver falls back to cloudflare', () => {
  const inventory = inv({
    guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.10', port: 8080, subdomains: ['app'] }],
  });
  const content = render(buildRoutes(inventory), buildProxyContext(inventory), CONFIG_PATH)[0].content;
  const doc = parse(content) as { http: { routers: Record<string, { tls: { certResolver: string } }> } };
  assert.equal(doc.http.routers['bellhop-route-app-example-com'].tls.certResolver, 'cloudflare');
});

// --- render: forward-auth objects (User Story 2, contract "Rendered file:
// example" -- the *media* entry, and research.md R6/R7/R9) -----------------

// The outpost every forward-gated route below addresses -- distinct from
// ctx()'s own default (no outpost), since most US1 tests never needed one.
function gatedCtx(overrides: Partial<ProxyContext> = {}): ProxyContext {
  return ctx({ outpost: { ip: '192.0.2.5', port: 9000 }, ...overrides });
}

const BELLHOP_AUTHENTIK_MIDDLEWARE = {
  forwardAuth: {
    address: 'http://192.0.2.5:9000/outpost.goauthentik.io/auth/traefik',
    trustForwardHeader: true,
    authResponseHeaders: ['X-authentik-username', 'X-authentik-groups', 'X-authentik-email', 'X-authentik-name', 'X-authentik-uid'],
  },
};
const BELLHOP_AUTHENTIK_OUTPOST_SERVICE = { loadBalancer: { servers: [{ url: 'http://192.0.2.5:9000' }] } };

function mediaRoute(overrides: Partial<ProxyRoute> = {}): ProxyRoute {
  return route({
    owner: { type: 'guest', name: 'media' },
    hostnames: ['media.example.com'],
    backend: { ip: '192.0.2.21', port: 443, insecureTls: true },
    auth: {
      mode: 'forward',
      exemptPaths: [parsePathPattern('/health'), parsePathPattern('/api/*')],
      rawExemptPaths: ['/health', '/api/*'],
    },
    ...overrides,
  });
}

test('render: the contract example\'s media entry -- main router middlewares/outpost router/exempt router/services/shared middleware', () => {
  const content = renderOne(mediaRoute(), gatedCtx());
  const doc = parse(content) as {
    http: {
      routers: Record<string, { rule: string; entryPoints: string[]; service: string; middlewares: string[]; tls: { certResolver: string } }>;
      services: Record<string, unknown>;
      middlewares: Record<string, unknown>;
      serversTransports: Record<string, unknown>;
    };
  };

  const mainRouter = doc.http.routers['bellhop-route-media-example-com'];
  assert.deepEqual(mainRouter, {
    rule: 'Host(`media.example.com`)',
    entryPoints: ['websecure'],
    service: 'bellhop-route-media-example-com',
    middlewares: ['bellhop-forwarded-port', 'bellhop-authentik'],
    tls: { certResolver: 'cloudflare' },
  });

  const outpostRouter = doc.http.routers['bellhop-outpost-media-example-com'];
  assert.deepEqual(outpostRouter, {
    rule: '(Host(`media.example.com`)) && PathPrefix(`/outpost.goauthentik.io/`)',
    entryPoints: ['websecure'],
    service: 'bellhop-authentik-outpost',
    middlewares: ['bellhop-forwarded-port'],
    tls: { certResolver: 'cloudflare' },
  });

  const exemptRouter = doc.http.routers['bellhop-exempt-media-example-com'];
  assert.deepEqual(exemptRouter, {
    rule: '(Host(`media.example.com`)) && (Path(`/health`) || PathPrefix(`/api/`))',
    entryPoints: ['websecure'],
    service: 'bellhop-route-media-example-com',
    middlewares: ['bellhop-forwarded-port'],
    tls: { certResolver: 'cloudflare' },
  });

  assert.equal(Object.keys(doc.http.routers).length, 3);

  assert.deepEqual(doc.http.services['bellhop-route-media-example-com'], {
    loadBalancer: { servers: [{ url: 'https://192.0.2.21:443' }], serversTransport: 'bellhop-insecure-backend-tls' },
  });
  assert.deepEqual(doc.http.services['bellhop-authentik-outpost'], BELLHOP_AUTHENTIK_OUTPOST_SERVICE);

  assert.deepEqual(doc.http.middlewares['bellhop-authentik'], BELLHOP_AUTHENTIK_MIDDLEWARE);
  assert.deepEqual(doc.http.serversTransports['bellhop-insecure-backend-tls'], { insecureSkipVerify: true });
});

test('render: bellhop-authentik middleware is the second key in http.middlewares, after bellhop-forwarded-port and before the generation marker', () => {
  const content = renderOne(mediaRoute(), gatedCtx());
  const doc = parse(content) as { http: { middlewares: Record<string, unknown> } };
  const names = Object.keys(doc.http.middlewares);
  assert.deepEqual(names.slice(0, 2), ['bellhop-forwarded-port', 'bellhop-authentik']);
  assert.ok(names[2].startsWith('bellhop-generation-'));
  assert.equal(names.length, 3);
});

test('render: a bare /* exemption removes bellhop-authentik from the main router and renders no exempt router, but keeps the outpost router', () => {
  const content = renderOne(
    mediaRoute({
      auth: { mode: 'forward', exemptPaths: [parsePathPattern('/*')], rawExemptPaths: ['/*'] },
    }),
    gatedCtx()
  );
  const doc = parse(content) as { http: { routers: Record<string, { middlewares: string[] }> } };
  assert.deepEqual(doc.http.routers['bellhop-route-media-example-com'].middlewares, ['bellhop-forwarded-port']);
  assert.equal(doc.http.routers['bellhop-exempt-media-example-com'], undefined);
  assert.ok(doc.http.routers['bellhop-outpost-media-example-com'], 'outpost router must still be rendered');
});

test('render: an outpost-namespace exempt pattern is skipped, so with only that pattern no exempt router is rendered (but bellhop-authentik stays on the main router)', () => {
  const content = renderOne(
    mediaRoute({
      auth: {
        mode: 'forward',
        exemptPaths: [parsePathPattern('/outpost.goauthentik.io/*')],
        rawExemptPaths: ['/outpost.goauthentik.io/*'],
      },
    }),
    gatedCtx()
  );
  const doc = parse(content) as { http: { routers: Record<string, { middlewares: string[] }> } };
  assert.deepEqual(doc.http.routers['bellhop-route-media-example-com'].middlewares, ['bellhop-forwarded-port', 'bellhop-authentik']);
  assert.equal(doc.http.routers['bellhop-exempt-media-example-com'], undefined);
  assert.ok(doc.http.routers['bellhop-outpost-media-example-com'], 'outpost router must still be rendered');
});

test('render: an exact outpost-namespace path (no trailing /*) is also skipped', () => {
  const content = renderOne(
    mediaRoute({
      auth: {
        mode: 'forward',
        exemptPaths: [parsePathPattern('/outpost.goauthentik.io')],
        rawExemptPaths: ['/outpost.goauthentik.io'],
      },
    }),
    gatedCtx()
  );
  const doc = parse(content) as { http: { routers: Record<string, unknown> } };
  assert.equal(doc.http.routers['bellhop-exempt-media-example-com'], undefined);
});

test('render: duplicate exempt patterns (same kind+path) are deduplicated into one Path()/PathPrefix() term', () => {
  const content = renderOne(
    mediaRoute({
      auth: {
        mode: 'forward',
        exemptPaths: [parsePathPattern('/health'), parsePathPattern('/health')],
        rawExemptPaths: ['/health', '/health'],
      },
    }),
    gatedCtx()
  );
  const doc = parse(content) as { http: { routers: Record<string, { rule: string }> } };
  assert.equal(doc.http.routers['bellhop-exempt-media-example-com'].rule, '(Host(`media.example.com`)) && (Path(`/health`))');
});

test('render: an OIDC route gets no forward-auth objects at all -- no outpost/exempt router, no bellhop-authentik middleware or outpost service', () => {
  const content = renderOne(mediaRoute({ auth: { mode: 'oidc' } }), gatedCtx());
  const doc = parse(content) as {
    http: { routers: Record<string, { middlewares: string[] }>; services: Record<string, unknown>; middlewares: Record<string, unknown> };
  };
  assert.deepEqual(Object.keys(doc.http.routers), ['bellhop-route-media-example-com']);
  assert.deepEqual(doc.http.routers['bellhop-route-media-example-com'].middlewares, ['bellhop-forwarded-port']);
  assert.equal(doc.http.services['bellhop-authentik-outpost'], undefined);
  assert.equal(doc.http.middlewares['bellhop-authentik'], undefined);
});

// --- render: the whole contract example (wiki + media together) ------------

test('render: the whole contract example (wiki ungated + media forward-gated) renders to the documented structure', () => {
  const wiki = route({
    owner: { type: 'guest', name: 'wiki' },
    hostnames: ['wiki.example.com', 'docs.example.com'],
    backend: { ip: '192.0.2.20', port: 8080, insecureTls: false },
  });
  const media = mediaRoute();
  const contractCtx = gatedCtx();

  const expectedRouters = {
    'bellhop-route-wiki-example-com': {
      rule: 'Host(`wiki.example.com`) || Host(`docs.example.com`)',
      entryPoints: ['websecure'],
      service: 'bellhop-route-wiki-example-com',
      middlewares: ['bellhop-forwarded-port'],
      tls: { certResolver: 'cloudflare' },
    },
    'bellhop-route-media-example-com': {
      rule: 'Host(`media.example.com`)',
      entryPoints: ['websecure'],
      service: 'bellhop-route-media-example-com',
      middlewares: ['bellhop-forwarded-port', 'bellhop-authentik'],
      tls: { certResolver: 'cloudflare' },
    },
    'bellhop-outpost-media-example-com': {
      rule: '(Host(`media.example.com`)) && PathPrefix(`/outpost.goauthentik.io/`)',
      entryPoints: ['websecure'],
      service: 'bellhop-authentik-outpost',
      middlewares: ['bellhop-forwarded-port'],
      tls: { certResolver: 'cloudflare' },
    },
    'bellhop-exempt-media-example-com': {
      rule: '(Host(`media.example.com`)) && (Path(`/health`) || PathPrefix(`/api/`))',
      entryPoints: ['websecure'],
      service: 'bellhop-route-media-example-com',
      middlewares: ['bellhop-forwarded-port'],
      tls: { certResolver: 'cloudflare' },
    },
  };

  const expectedServices = {
    'bellhop-route-wiki-example-com': { loadBalancer: { servers: [{ url: 'http://192.0.2.20:8080' }] } },
    'bellhop-route-media-example-com': {
      loadBalancer: { servers: [{ url: 'https://192.0.2.21:443' }], serversTransport: 'bellhop-insecure-backend-tls' },
    },
    'bellhop-authentik-outpost': BELLHOP_AUTHENTIK_OUTPOST_SERVICE,
  };

  const expectedMiddlewaresWithoutMarker = {
    'bellhop-forwarded-port': { headers: { customRequestHeaders: { 'X-Forwarded-Port': '443' } } },
    'bellhop-authentik': BELLHOP_AUTHENTIK_MIDDLEWARE,
  };

  const expectedServersTransports = { 'bellhop-insecure-backend-tls': { insecureSkipVerify: true } };

  // The marker hash is computed independently here, via the `yaml` package's
  // own `stringify` (a third-party function, not render()'s own hashing
  // logic) over a hand-written object mirroring render()'s two-pass
  // construction -- same convention as the existing wiki-only test above,
  // just extended to the full two-route, forward-auth shape.
  const httpWithoutMarker = {
    routers: expectedRouters,
    services: expectedServices,
    middlewares: expectedMiddlewaresWithoutMarker,
    serversTransports: expectedServersTransports,
  };
  const contentWithoutMarker = `${HEADER}\n${stringify({ http: httpWithoutMarker })}`;
  const hash = sha256First12(contentWithoutMarker);
  const markerName = `bellhop-generation-${hash}`;

  const expectedDoc = {
    http: {
      routers: expectedRouters,
      services: expectedServices,
      middlewares: {
        ...expectedMiddlewaresWithoutMarker,
        [markerName]: { headers: { customRequestHeaders: { 'X-Bellhop-Generation': hash } } },
      },
      serversTransports: expectedServersTransports,
    },
  };

  const content = render([wiki, media], contractCtx, CONFIG_PATH)[0].content;
  assert.equal(content.split('\n')[0], HEADER);
  assert.deepEqual(parse(content), expectedDoc);
});
