// User Story 1 (issue #35): render tests pinned against
// specs/015-traefik-proxy-driver/contracts/traefik-driver.md's "Rendered
// file: example" -- the *wiki* (ungated) entry's shape only. Forward-auth/
// outpost/exempt objects are User Story 2 and are exercised in a later test
// file, not here.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { parse, stringify } from 'yaml';
import { mkdtempSync, writeFileSync, chmodSync, readFileSync, existsSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, delimiter, resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { buildRoutes, buildProxyContext, parsePathPattern, type ProxyContext, type ProxyRoute } from '../../../../src/lib/proxy/routes.ts';
import {
  buildApiCheck,
  encodeHostname,
  generationMarkerName,
  render,
  routeName,
  routerNames,
  ruleValue,
  traefikDriver,
} from '../../../../src/lib/proxy/drivers/traefik.ts';
import { buildFileDriverScript } from '../../../../src/lib/proxy/file-driver.ts';
import { FakeSSHClient } from '../../../support/fake-ssh-client.ts';
import type { Inventory } from '../../../../src/lib/inventory.ts';

const HEADER = '# Generated by Bellhop sync-proxy. Do not edit: this file is replaced on every apply.';
const CONFIG_PATH = '/etc/traefik/dynamic/bellhop.yml';

function ctx(overrides: Partial<ProxyContext> = {}): ProxyContext {
  return {
    externalPort: 443,
    tls: {
      certificatePath: '/etc/letsencrypt/live/example.com/fullchain.pem',
      keyPath: '/etc/letsencrypt/live/example.com/privkey.pem',
    },
    certResolver: 'cloudflare',
    ...overrides,
  };
}

function route(overrides: Partial<ProxyRoute> & { owner: ProxyRoute['owner'] }): ProxyRoute {
  return {
    hostnames: [`${overrides.owner.name}.example.com`],
    backend: { ip: '192.0.2.30', port: 80, insecureTls: false },
    auth: { mode: 'ungated' },
    ...overrides,
  };
}

function renderOne(r: ProxyRoute, c: ProxyContext = ctx()): string {
  return render([r], c, CONFIG_PATH)[0].content;
}

// The forwarded-port middleware body, present in every rendered file
// regardless of routes (research.md R7).
const FORWARDED_PORT_MIDDLEWARE = ['    bellhop-forwarded-port:', '      headers:', '        customRequestHeaders:', '          X-Forwarded-Port: "443"'];

function sha256First12(content: string): string {
  return createHash('sha256').update(content).digest('hex').slice(0, 12);
}

// --- encodeHostname / ruleValue / name helpers -------------------------------

test('encodeHostname: lowercases, doubles "-", then turns "." into "-" -- injective, so two different hostnames never collide', () => {
  assert.equal(encodeHostname('Wiki.Example.com'), 'wiki-example-com');
  assert.equal(encodeHostname('a.b-c.example.com'), 'a-b--c-example-com');
  assert.equal(encodeHostname('a-b.c.example.com'), 'a--b-c-example-com');
  assert.notEqual(encodeHostname('a.b-c.example.com'), encodeHostname('a-b.c.example.com'));
});

test('routeName: bellhop-route-<encoded canonical hostname>', () => {
  assert.equal(routeName('wiki.example.com'), 'bellhop-route-wiki-example-com');
});

test('ruleValue: no backtick -> backtick-quoted', () => {
  assert.equal(ruleValue('wiki.example.com'), '`wiki.example.com`');
  assert.equal(ruleValue('/health'), '`/health`');
});

test('ruleValue: a value containing a backtick -> JSON.stringify (double-quoted Go-style escaping)', () => {
  const value = '/a`b"c\\d';
  assert.equal(ruleValue(value), JSON.stringify(value));
  assert.equal(ruleValue(value), '"/a`b\\"c\\\\d"');
});

// --- render: the contract's *wiki* entry (ungated, two hostnames) -----------

test('render: the contract example\'s wiki entry -- rule order, entry point, service, middlewares, tls.certResolver, and http service URL', () => {
  const wiki = route({
    owner: { type: 'guest', name: 'wiki' },
    hostnames: ['wiki.example.com', 'docs.example.com'],
    backend: { ip: '192.0.2.20', port: 8080, insecureTls: false },
  });

  // The body without the marker, built the same way render() computes its
  // own hash input -- the test recomputes the hash independently (via
  // node:crypto directly, not by importing render()'s internals) so this is
  // a real pin on the hashing behavior, not a tautology.
  const bodyWithoutMarker = [
    'http:',
    '  routers:',
    '    bellhop-route-wiki-example-com:',
    '      rule: Host(`wiki.example.com`) || Host(`docs.example.com`)',
    '      entryPoints:',
    '        - websecure',
    '      service: bellhop-route-wiki-example-com',
    '      middlewares:',
    '        - bellhop-forwarded-port',
    '      tls:',
    '        certResolver: cloudflare',
    '  services:',
    '    bellhop-route-wiki-example-com:',
    '      loadBalancer:',
    '        servers:',
    '          - url: http://192.0.2.20:8080',
    '  middlewares:',
    ...FORWARDED_PORT_MIDDLEWARE,
    '',
  ].join('\n');
  const contentWithoutMarker = `${HEADER}\n${bodyWithoutMarker}`;
  const hash = sha256First12(contentWithoutMarker);

  const expected = [
    HEADER,
    'http:',
    '  routers:',
    '    bellhop-route-wiki-example-com:',
    '      rule: Host(`wiki.example.com`) || Host(`docs.example.com`)',
    '      entryPoints:',
    '        - websecure',
    '      service: bellhop-route-wiki-example-com',
    '      middlewares:',
    '        - bellhop-forwarded-port',
    '      tls:',
    '        certResolver: cloudflare',
    '  services:',
    '    bellhop-route-wiki-example-com:',
    '      loadBalancer:',
    '        servers:',
    '          - url: http://192.0.2.20:8080',
    '  middlewares:',
    ...FORWARDED_PORT_MIDDLEWARE,
    `    bellhop-generation-${hash}:`,
    '      headers:',
    '        customRequestHeaders:',
    `          X-Bellhop-Generation: "${hash}"`,
    '',
  ].join('\n');

  assert.equal(renderOne(wiki), expected);
});

test('render: entry point is always [websecure], and middlewares lists bellhop-forwarded-port only for an ungated route', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' } }));
  const doc = parse(content) as { http: { routers: Record<string, { entryPoints: string[]; middlewares: string[] }> } };
  const router = doc.http.routers['bellhop-route-app-example-com'];
  assert.deepEqual(router.entryPoints, ['websecure']);
  assert.deepEqual(router.middlewares, ['bellhop-forwarded-port']);
});

// --- render: backend scheme (research.md R8) --------------------------------

test('render: a plain port (not 443, not insecureTls) -> http:// service URL, no serversTransport, no serversTransports block', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.10', port: 8080, insecureTls: false } }));
  const doc = parse(content) as { http: { services: Record<string, { loadBalancer: { servers: { url: string }[]; serversTransport?: string } }>; serversTransports?: unknown } };
  const service = doc.http.services['bellhop-route-app-example-com'];
  assert.equal(service.loadBalancer.servers[0].url, 'http://192.0.2.10:8080');
  assert.equal(service.loadBalancer.serversTransport, undefined);
  assert.equal(doc.http.serversTransports, undefined);
});

test('render: a port-443 backend -> https:// service URL, but no serversTransport (the default transport already verifies)', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.10', port: 443, insecureTls: false } }));
  const doc = parse(content) as { http: { services: Record<string, { loadBalancer: { servers: { url: string }[]; serversTransport?: string } }>; serversTransports?: unknown } };
  const service = doc.http.services['bellhop-route-app-example-com'];
  assert.equal(service.loadBalancer.servers[0].url, 'https://192.0.2.10:443');
  assert.equal(service.loadBalancer.serversTransport, undefined);
  assert.equal(doc.http.serversTransports, undefined);
});

test('render: insecureTls -> https:// service URL, serversTransport bellhop-insecure-backend-tls, and the shared serversTransports.insecureSkipVerify block', () => {
  const content = renderOne(route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.10', port: 8443, insecureTls: true } }));
  const doc = parse(content) as {
    http: {
      services: Record<string, { loadBalancer: { servers: { url: string }[]; serversTransport?: string } }>;
      serversTransports?: Record<string, { insecureSkipVerify: boolean }>;
    };
  };
  const service = doc.http.services['bellhop-route-app-example-com'];
  assert.equal(service.loadBalancer.servers[0].url, 'https://192.0.2.10:8443');
  assert.equal(service.loadBalancer.serversTransport, 'bellhop-insecure-backend-tls');
  assert.deepEqual(doc.http.serversTransports, { 'bellhop-insecure-backend-tls': { insecureSkipVerify: true } });
});

// --- render: OIDC renders identically to ungated ----------------------------

test('render: an OIDC route renders identically to the same route ungated -- no auth objects exist yet (User Story 2)', () => {
  const ungated = route({ owner: { type: 'externalSite', name: 'nas' }, auth: { mode: 'ungated' } });
  const oidc = route({ owner: { type: 'externalSite', name: 'nas' }, auth: { mode: 'oidc' } });
  assert.equal(renderOne(ungated), renderOne(oidc));
});

// --- render: zero routes -----------------------------------------------------

test('render: zero routes -> header plus http.middlewares holding only bellhop-forwarded-port and the marker -- no routers/services/serversTransports', () => {
  const content = render([], ctx(), CONFIG_PATH)[0].content;
  assert.equal(content.split('\n')[0], HEADER);
  const doc = parse(content) as {
    http: { routers?: unknown; services?: unknown; serversTransports?: unknown; middlewares: Record<string, unknown> };
  };
  assert.equal(doc.http.routers, undefined);
  assert.equal(doc.http.services, undefined);
  assert.equal(doc.http.serversTransports, undefined);
  const names = Object.keys(doc.http.middlewares);
  assert.equal(names.length, 2);
  assert.equal(names[0], 'bellhop-forwarded-port');
  assert.ok(names[1].startsWith('bellhop-generation-'), `expected a generation marker, got '${names[1]}'`);
});

// --- render: FileSpec shape --------------------------------------------------

test('render: returns one owned, atomic FileSpec at configPath, owned by its header', () => {
  const files = render([route({ owner: { type: 'guest', name: 'app' } })], ctx(), CONFIG_PATH);
  assert.equal(files.length, 1);
  assert.equal(files[0].path, CONFIG_PATH);
  assert.equal(files[0].mode, 'owned');
  assert.equal(files[0].ownedHeader, HEADER);
  assert.equal(files[0].atomic, true);
});

// --- generation marker: stability and change detection (research.md R3) ----

test('generationMarkerName: stable across two renders of the same routes, and different when a route changes', () => {
  const routes = [route({ owner: { type: 'guest', name: 'app' } })];
  const first = render(routes, ctx(), CONFIG_PATH)[0].content;
  const second = render(routes, ctx(), CONFIG_PATH)[0].content;
  assert.equal(first, second, 'two renders of the same input must be byte-identical');
  assert.equal(generationMarkerName(first), generationMarkerName(second));

  const changed = [route({ owner: { type: 'guest', name: 'app' }, backend: { ip: '192.0.2.99', port: 80, insecureTls: false } })];
  const third = render(changed, ctx(), CONFIG_PATH)[0].content;
  assert.notEqual(generationMarkerName(first), generationMarkerName(third), 'a changed route must change the marker hash');
});

test('routerNames: every router name, in render order', () => {
  const routes = [route({ owner: { type: 'guest', name: 'zeta' } }), route({ owner: { type: 'guest', name: 'alpha' } })];
  const content = render(routes, ctx(), CONFIG_PATH)[0].content;
  assert.deepEqual(routerNames(content), ['bellhop-route-zeta-example-com', 'bellhop-route-alpha-example-com']);
});

test('routerNames: empty for zero routes', () => {
  const content = render([], ctx(), CONFIG_PATH)[0].content;
  assert.deepEqual(routerNames(content), []);
});

// --- render: driven through buildRoutes/buildProxyContext, like sync-proxy --

function inv(overrides: Partial<Inventory> = {}): Inventory {
  return {
    domain: 'example.com',
    hosts: [{ name: 'pve1', ssh_target: '192.0.2.1', ssh_user: 'root', proxy: true }],
    guests: [],
    ...overrides,
  };
}

test('render via buildRoutes/buildProxyContext: proxyCertResolver flows into every router\'s tls.certResolver', () => {
  const inventory = inv({
    proxyCertResolver: 'my-resolver',
    guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.10', port: 8080, subdomains: ['app'] }],
  });
  const content = render(buildRoutes(inventory), buildProxyContext(inventory), CONFIG_PATH)[0].content;
  const doc = parse(content) as { http: { routers: Record<string, { tls: { certResolver: string } }> } };
  assert.equal(doc.http.routers['bellhop-route-app-example-com'].tls.certResolver, 'my-resolver');
});

test('render via buildRoutes/buildProxyContext: an unset proxyCertResolver falls back to cloudflare', () => {
  const inventory = inv({
    guests: [{ name: 'app-lxc', type: 'lxc', vmid: 100, host: 'pve1', ip: '192.0.2.10', port: 8080, subdomains: ['app'] }],
  });
  const content = render(buildRoutes(inventory), buildProxyContext(inventory), CONFIG_PATH)[0].content;
  const doc = parse(content) as { http: { routers: Record<string, { tls: { certResolver: string } }> } };
  assert.equal(doc.http.routers['bellhop-route-app-example-com'].tls.certResolver, 'cloudflare');
});

// --- render: forward-auth objects (User Story 2, contract "Rendered file:
// example" -- the *media* entry, and research.md R6/R7/R9) -----------------

// The outpost every forward-gated route below addresses -- distinct from
// ctx()'s own default (no outpost), since most US1 tests never needed one.
function gatedCtx(overrides: Partial<ProxyContext> = {}): ProxyContext {
  return ctx({ outpost: { ip: '192.0.2.5', port: 9000 }, ...overrides });
}

const BELLHOP_AUTHENTIK_MIDDLEWARE = {
  forwardAuth: {
    address: 'http://192.0.2.5:9000/outpost.goauthentik.io/auth/traefik',
    trustForwardHeader: true,
    authResponseHeaders: ['X-authentik-username', 'X-authentik-groups', 'X-authentik-email', 'X-authentik-name', 'X-authentik-uid'],
  },
};
const BELLHOP_AUTHENTIK_OUTPOST_SERVICE = { loadBalancer: { servers: [{ url: 'http://192.0.2.5:9000' }] } };

function mediaRoute(overrides: Partial<ProxyRoute> = {}): ProxyRoute {
  return route({
    owner: { type: 'guest', name: 'media' },
    hostnames: ['media.example.com'],
    backend: { ip: '192.0.2.21', port: 443, insecureTls: true },
    auth: {
      mode: 'forward',
      exemptPaths: [parsePathPattern('/health'), parsePathPattern('/api/*')],
      rawExemptPaths: ['/health', '/api/*'],
    },
    ...overrides,
  });
}

test('render: the contract example\'s media entry -- main router middlewares/outpost router/exempt router/services/shared middleware', () => {
  const content = renderOne(mediaRoute(), gatedCtx());
  const doc = parse(content) as {
    http: {
      routers: Record<string, { rule: string; entryPoints: string[]; service: string; middlewares: string[]; tls: { certResolver: string } }>;
      services: Record<string, unknown>;
      middlewares: Record<string, unknown>;
      serversTransports: Record<string, unknown>;
    };
  };

  const mainRouter = doc.http.routers['bellhop-route-media-example-com'];
  assert.deepEqual(mainRouter, {
    rule: 'Host(`media.example.com`)',
    entryPoints: ['websecure'],
    service: 'bellhop-route-media-example-com',
    middlewares: ['bellhop-forwarded-port', 'bellhop-authentik'],
    tls: { certResolver: 'cloudflare' },
  });

  const outpostRouter = doc.http.routers['bellhop-outpost-media-example-com'];
  assert.deepEqual(outpostRouter, {
    rule: '(Host(`media.example.com`)) && PathPrefix(`/outpost.goauthentik.io/`)',
    entryPoints: ['websecure'],
    service: 'bellhop-authentik-outpost',
    middlewares: ['bellhop-forwarded-port'],
    tls: { certResolver: 'cloudflare' },
  });

  const exemptRouter = doc.http.routers['bellhop-exempt-media-example-com'];
  assert.deepEqual(exemptRouter, {
    rule: '(Host(`media.example.com`)) && (Path(`/health`) || PathPrefix(`/api/`))',
    entryPoints: ['websecure'],
    service: 'bellhop-route-media-example-com',
    middlewares: ['bellhop-forwarded-port'],
    tls: { certResolver: 'cloudflare' },
  });

  assert.equal(Object.keys(doc.http.routers).length, 3);

  assert.deepEqual(doc.http.services['bellhop-route-media-example-com'], {
    loadBalancer: { servers: [{ url: 'https://192.0.2.21:443' }], serversTransport: 'bellhop-insecure-backend-tls' },
  });
  assert.deepEqual(doc.http.services['bellhop-authentik-outpost'], BELLHOP_AUTHENTIK_OUTPOST_SERVICE);

  assert.deepEqual(doc.http.middlewares['bellhop-authentik'], BELLHOP_AUTHENTIK_MIDDLEWARE);
  assert.deepEqual(doc.http.serversTransports['bellhop-insecure-backend-tls'], { insecureSkipVerify: true });
});

test('render: bellhop-authentik middleware is the second key in http.middlewares, after bellhop-forwarded-port and before the generation marker', () => {
  const content = renderOne(mediaRoute(), gatedCtx());
  const doc = parse(content) as { http: { middlewares: Record<string, unknown> } };
  const names = Object.keys(doc.http.middlewares);
  assert.deepEqual(names.slice(0, 2), ['bellhop-forwarded-port', 'bellhop-authentik']);
  assert.ok(names[2].startsWith('bellhop-generation-'));
  assert.equal(names.length, 3);
});

test('render: a bare /* exemption removes bellhop-authentik from the main router and renders no exempt router, but keeps the outpost router', () => {
  const content = renderOne(
    mediaRoute({
      auth: { mode: 'forward', exemptPaths: [parsePathPattern('/*')], rawExemptPaths: ['/*'] },
    }),
    gatedCtx()
  );
  const doc = parse(content) as { http: { routers: Record<string, { middlewares: string[] }> } };
  assert.deepEqual(doc.http.routers['bellhop-route-media-example-com'].middlewares, ['bellhop-forwarded-port']);
  assert.equal(doc.http.routers['bellhop-exempt-media-example-com'], undefined);
  assert.ok(doc.http.routers['bellhop-outpost-media-example-com'], 'outpost router must still be rendered');
});

test('render: an outpost-namespace exempt pattern is skipped, so with only that pattern no exempt router is rendered (but bellhop-authentik stays on the main router)', () => {
  const content = renderOne(
    mediaRoute({
      auth: {
        mode: 'forward',
        exemptPaths: [parsePathPattern('/outpost.goauthentik.io/*')],
        rawExemptPaths: ['/outpost.goauthentik.io/*'],
      },
    }),
    gatedCtx()
  );
  const doc = parse(content) as { http: { routers: Record<string, { middlewares: string[] }> } };
  assert.deepEqual(doc.http.routers['bellhop-route-media-example-com'].middlewares, ['bellhop-forwarded-port', 'bellhop-authentik']);
  assert.equal(doc.http.routers['bellhop-exempt-media-example-com'], undefined);
  assert.ok(doc.http.routers['bellhop-outpost-media-example-com'], 'outpost router must still be rendered');
});

test('render: an exact outpost-namespace path (no trailing /*) is also skipped', () => {
  const content = renderOne(
    mediaRoute({
      auth: {
        mode: 'forward',
        exemptPaths: [parsePathPattern('/outpost.goauthentik.io')],
        rawExemptPaths: ['/outpost.goauthentik.io'],
      },
    }),
    gatedCtx()
  );
  const doc = parse(content) as { http: { routers: Record<string, unknown> } };
  assert.equal(doc.http.routers['bellhop-exempt-media-example-com'], undefined);
});

test('render: duplicate exempt patterns (same kind+path) are deduplicated into one Path()/PathPrefix() term', () => {
  const content = renderOne(
    mediaRoute({
      auth: {
        mode: 'forward',
        exemptPaths: [parsePathPattern('/health'), parsePathPattern('/health')],
        rawExemptPaths: ['/health', '/health'],
      },
    }),
    gatedCtx()
  );
  const doc = parse(content) as { http: { routers: Record<string, { rule: string }> } };
  assert.equal(doc.http.routers['bellhop-exempt-media-example-com'].rule, '(Host(`media.example.com`)) && (Path(`/health`))');
});

test('render: an OIDC route gets no forward-auth objects at all -- no outpost/exempt router, no bellhop-authentik middleware or outpost service', () => {
  const content = renderOne(mediaRoute({ auth: { mode: 'oidc' } }), gatedCtx());
  const doc = parse(content) as {
    http: { routers: Record<string, { middlewares: string[] }>; services: Record<string, unknown>; middlewares: Record<string, unknown> };
  };
  assert.deepEqual(Object.keys(doc.http.routers), ['bellhop-route-media-example-com']);
  assert.deepEqual(doc.http.routers['bellhop-route-media-example-com'].middlewares, ['bellhop-forwarded-port']);
  assert.equal(doc.http.services['bellhop-authentik-outpost'], undefined);
  assert.equal(doc.http.middlewares['bellhop-authentik'], undefined);
});

// --- render: the whole contract example (wiki + media together) ------------

test('render: the whole contract example (wiki ungated + media forward-gated) renders to the documented structure', () => {
  const wiki = route({
    owner: { type: 'guest', name: 'wiki' },
    hostnames: ['wiki.example.com', 'docs.example.com'],
    backend: { ip: '192.0.2.20', port: 8080, insecureTls: false },
  });
  const media = mediaRoute();
  const contractCtx = gatedCtx();

  const expectedRouters = {
    'bellhop-route-wiki-example-com': {
      rule: 'Host(`wiki.example.com`) || Host(`docs.example.com`)',
      entryPoints: ['websecure'],
      service: 'bellhop-route-wiki-example-com',
      middlewares: ['bellhop-forwarded-port'],
      tls: { certResolver: 'cloudflare' },
    },
    'bellhop-route-media-example-com': {
      rule: 'Host(`media.example.com`)',
      entryPoints: ['websecure'],
      service: 'bellhop-route-media-example-com',
      middlewares: ['bellhop-forwarded-port', 'bellhop-authentik'],
      tls: { certResolver: 'cloudflare' },
    },
    'bellhop-outpost-media-example-com': {
      rule: '(Host(`media.example.com`)) && PathPrefix(`/outpost.goauthentik.io/`)',
      entryPoints: ['websecure'],
      service: 'bellhop-authentik-outpost',
      middlewares: ['bellhop-forwarded-port'],
      tls: { certResolver: 'cloudflare' },
    },
    'bellhop-exempt-media-example-com': {
      rule: '(Host(`media.example.com`)) && (Path(`/health`) || PathPrefix(`/api/`))',
      entryPoints: ['websecure'],
      service: 'bellhop-route-media-example-com',
      middlewares: ['bellhop-forwarded-port'],
      tls: { certResolver: 'cloudflare' },
    },
  };

  const expectedServices = {
    'bellhop-route-wiki-example-com': { loadBalancer: { servers: [{ url: 'http://192.0.2.20:8080' }] } },
    'bellhop-route-media-example-com': {
      loadBalancer: { servers: [{ url: 'https://192.0.2.21:443' }], serversTransport: 'bellhop-insecure-backend-tls' },
    },
    'bellhop-authentik-outpost': BELLHOP_AUTHENTIK_OUTPOST_SERVICE,
  };

  const expectedMiddlewaresWithoutMarker = {
    'bellhop-forwarded-port': { headers: { customRequestHeaders: { 'X-Forwarded-Port': '443' } } },
    'bellhop-authentik': BELLHOP_AUTHENTIK_MIDDLEWARE,
  };

  const expectedServersTransports = { 'bellhop-insecure-backend-tls': { insecureSkipVerify: true } };

  // The marker hash is computed independently here, via the `yaml` package's
  // own `stringify` (a third-party function, not render()'s own hashing
  // logic) over a hand-written object mirroring render()'s two-pass
  // construction -- same convention as the existing wiki-only test above,
  // just extended to the full two-route, forward-auth shape.
  const httpWithoutMarker = {
    routers: expectedRouters,
    services: expectedServices,
    middlewares: expectedMiddlewaresWithoutMarker,
    serversTransports: expectedServersTransports,
  };
  const contentWithoutMarker = `${HEADER}\n${stringify({ http: httpWithoutMarker })}`;
  const hash = sha256First12(contentWithoutMarker);
  const markerName = `bellhop-generation-${hash}`;

  const expectedDoc = {
    http: {
      routers: expectedRouters,
      services: expectedServices,
      middlewares: {
        ...expectedMiddlewaresWithoutMarker,
        [markerName]: { headers: { customRequestHeaders: { 'X-Bellhop-Generation': hash } } },
      },
      serversTransports: expectedServersTransports,
    },
  };

  const content = render([wiki, media], contractCtx, CONFIG_PATH)[0].content;
  assert.equal(content.split('\n')[0], HEADER);
  assert.deepEqual(parse(content), expectedDoc);
});

// --- buildApiCheck (User Story 3, research.md R2-R4/R12) --------------------
// The opt-in post-write API check sent as the apply script's validate step
// when proxyApiUrl is set: poll the file's generation marker until it
// answers 200 (proving Traefik loaded *this* rendered version), then fetch
// every router by exact name and require "status":"enabled", collecting
// every unhealthy one before failing (contracts/traefik-driver.md "Validate
// step (proxyApiUrl set)").

function routesNamed(...names: string[]): ProxyRoute[] {
  return names.map((name) => route({ owner: { type: 'guest', name } }));
}

test('buildApiCheck: the API URL is single-quoted with a trailing slash stripped', () => {
  const content = render(routesNamed('app'), ctx(), CONFIG_PATH)[0].content;
  const check = buildApiCheck('http://127.0.0.1:8080/', CONFIG_PATH, content);
  assert.ok(check.includes("bellhop_api='http://127.0.0.1:8080'"), `expected the trailing slash stripped, got:\n${check}`);
});

test('buildApiCheck: polls the marker up to 30 times with a 1s sleep between attempts', () => {
  const content = render(routesNamed('app'), ctx(), CONFIG_PATH)[0].content;
  const marker = generationMarkerName(content);
  const check = buildApiCheck('http://127.0.0.1:8080', CONFIG_PATH, content);
  assert.match(check, /while :; do/);
  assert.ok(
    check.includes(
      `bellhop_code="$(curl -s -o /dev/null -w '%{http_code}' --max-time 5 "$bellhop_api/api/http/middlewares/${marker}@file")"`
    ),
    `expected a marker poll for ${marker}, got:\n${check}`
  );
  assert.ok(check.includes('[ "$bellhop_tries" -ge 30 ]'), 'gives up after 30 attempts');
  assert.ok(check.includes('sleep 1'), 'sleeps 1s between attempts');
});

test('buildApiCheck: the timeout message names the path, "unreachable" for a 000 code or "HTTP <code>" otherwise, and the API url', () => {
  const content = render([], ctx(), CONFIG_PATH)[0].content;
  const check = buildApiCheck('http://127.0.0.1:8080', CONFIG_PATH, content);
  assert.ok(check.includes('bellhop_result="unreachable"'), `expected an unreachable branch, got:\n${check}`);
  assert.ok(check.includes('bellhop_result="HTTP $bellhop_code"'), `expected an HTTP <code> branch, got:\n${check}`);
  assert.ok(
    check.includes(
      `printf 'Traefik did not load %s within 30 seconds (%s at %s)\\n' '${CONFIG_PATH}' "$bellhop_result" "$bellhop_api" >&2`
    ),
    `expected the exact timeout message, got:\n${check}`
  );
});

test('buildApiCheck: one curl + case block per router name, in render order, each reporting its own name and body when unhealthy', () => {
  const content = render(routesNamed('zeta', 'alpha'), ctx(), CONFIG_PATH)[0].content;
  const [r0, r1] = routerNames(content);
  const check = buildApiCheck('http://127.0.0.1:8080', CONFIG_PATH, content);
  const r0Index = check.indexOf(`/api/http/routers/${r0}@file`);
  const r1Index = check.indexOf(`/api/http/routers/${r1}@file`);
  assert.ok(r0Index !== -1 && r1Index !== -1 && r0Index < r1Index, `expected both router checks in render order, got:\n${check}`);
  assert.ok(check.includes(`bellhop_body="$(curl -s --max-time 5 "$bellhop_api/api/http/routers/${r0}@file")"`));
  assert.ok(check.includes(`*'"status":"enabled"'*) ;;`), 'passes a router whose body contains "status":"enabled"');
  assert.ok(
    check.includes(`*) printf 'Traefik router %s is not healthy: %s\\n' '${r0}' "$bellhop_body" >&2; bellhop_failed=1 ;;`),
    `expected the failure branch for ${r0}, got:\n${check}`
  );
  assert.ok(check.includes('exit "$bellhop_failed"'), 'exits with the accumulated failure flag, checking every router first');
});

test('buildApiCheck: zero routers -- waits for the marker only, then exits 0 immediately', () => {
  const content = render([], ctx(), CONFIG_PATH)[0].content;
  const check = buildApiCheck('http://127.0.0.1:8080', CONFIG_PATH, content);
  assert.ok(!check.includes('/api/http/routers/'), `expected no router checks at all, got:\n${check}`);
  assert.ok(check.includes('bellhop_failed=0\n  exit "$bellhop_failed"'), `expected an immediate exit, got:\n${check}`);
});

// --- traefikDriver.apply: wiring (T015) -------------------------------------
// With no proxyApiUrl the apply script has no validate step at all -- no
// curl anywhere; with it set, the script names the marker URL and one
// router URL per rendered router.

function driverDeps(inventory: Inventory, ssh: FakeSSHClient, configPath: string) {
  return { ssh, inventory, proxyHost: 'pve1', configPath };
}

test('traefikDriver.apply: no proxyApiUrl -- the apply script has no curl at all', async () => {
  const inventory: Inventory = { domain: 'example.com', hosts: [{ name: 'pve1', ssh_target: '192.0.2.1', ssh_user: 'root' }], guests: [] };
  const ssh = new FakeSSHClient(() => ({ stdout: '', stderr: '', code: 0 }));
  const deps = driverDeps(inventory, ssh, CONFIG_PATH);
  const plan = await traefikDriver.plan(routesNamed('app'), ctx(), deps);
  await traefikDriver.apply(plan, deps);
  assert.equal(ssh.history.length, 1);
  assert.ok(!ssh.history[0].command.includes('curl'), `expected no curl, got:\n${ssh.history[0].command}`);
});

test('traefikDriver.apply: proxyApiUrl set -- the apply script names the marker URL and one router URL per router', async () => {
  const inventory: Inventory = {
    domain: 'example.com',
    hosts: [{ name: 'pve1', ssh_target: '192.0.2.1', ssh_user: 'root' }],
    guests: [],
    proxyApiUrl: 'http://127.0.0.1:8080',
  };
  const ssh = new FakeSSHClient(() => ({ stdout: '', stderr: '', code: 0 }));
  const deps = driverDeps(inventory, ssh, CONFIG_PATH);
  const plan = await traefikDriver.plan(routesNamed('zeta', 'alpha'), ctx(), deps);
  const content = (plan.payload as { content: string }[])[0].content;
  const marker = generationMarkerName(content);
  const routers = routerNames(content);
  assert.equal(routers.length, 2, 'sanity: two routes render two routers');
  await traefikDriver.apply(plan, deps);
  const script = ssh.history[0].command;
  assert.ok(script.includes(`/api/http/middlewares/${marker}@file`), `expected the marker URL, got:\n${script}`);
  for (const router of routers) {
    assert.ok(script.includes(`/api/http/routers/${router}@file`), `expected a check for ${router}, got:\n${script}`);
  }
});

// --- buildApiCheck, executed (T015): stubbed curl/sleep on PATH -------------
// Follows test/lib/proxy/file-driver.test.ts's sh + stub pattern: the
// generated script is executed for real under `sh`, with only `curl` and
// `sleep` stubbed on PATH (real mktemp/cp/mv). The stub curl answers from
// the captured fixtures in test/fixtures/traefik/ by URL.

const FIXTURES_DIR = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..', '..', 'fixtures', 'traefik');
const ROUTER_ENABLED_FIXTURE = join(FIXTURES_DIR, 'router-enabled.json');
const ROUTER_DISABLED_FIXTURE = join(FIXTURES_DIR, 'router-disabled.json');
// A sentinel that never matches a real rendered router name, used as
// BELLHOP_TEST_BAD_ROUTER when every router in a test is meant to be healthy
// -- an empty value would make the stub's `*"$VAR"*` glob match everything.
const NO_BAD_ROUTER = 'bellhop-test-no-bad-router-sentinel';

function shAvailable(): boolean {
  const result = spawnSync('sh', ['-c', 'exit 0']);
  return result.error === undefined || result.error === null;
}

function posix(p: string): string {
  return p.replace(/\\/g, '/');
}

// A stub `curl` that answers a marker-middleware poll with a fixed HTTP
// status code, and a router-body fetch by `cat`-ing one of two fixture
// files -- the "bad" one when the URL contains $BELLHOP_TEST_BAD_ROUTER
// (an env var set per test), the "good" one otherwise.
function writeCurlStub(stubDir: string, markerCode: string): void {
  const curlPath = join(stubDir, 'curl');
  const script = [
    '#!/bin/sh',
    'url=""',
    'for a in "$@"; do url="$a"; done',
    'case "$url" in',
    '  */middlewares/*)',
    `    printf '%s' '${markerCode}'`,
    '    ;;',
    '  */routers/*)',
    '    case "$url" in',
    '      *"$BELLHOP_TEST_BAD_ROUTER"*)',
    `        cat '${posix(ROUTER_DISABLED_FIXTURE)}'`,
    '        ;;',
    '      *)',
    `        cat '${posix(ROUTER_ENABLED_FIXTURE)}'`,
    '        ;;',
    '    esac',
    '    ;;',
    'esac',
  ].join('\n');
  writeFileSync(curlPath, script);
  chmodSync(curlPath, 0o755);
}

function writeSleepStub(stubDir: string): void {
  const sleepPath = join(stubDir, 'sleep');
  writeFileSync(sleepPath, '#!/bin/sh\nexit 0\n');
  chmodSync(sleepPath, 0o755);
}

function buildTraefikApplyScript(
  routes: ProxyRoute[],
  configPath: string,
  apiUrl: string
): { script: string; content: string } {
  const files = render(routes, ctx(), configPath);
  const validateCommand = buildApiCheck(apiUrl, configPath, files[0].content);
  const script = buildFileDriverScript(files, validateCommand, null, 'Traefik API check');
  return { script, content: files[0].content };
}

test('buildApiCheck, executed: marker 200 on the first try and every router enabled -> exit 0, the new file is kept', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }
  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-traefik-api-check-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-traefik-api-check-stubs-'));
  const configPath = posix(join(tmpDir, 'bellhop.yml'));
  writeFileSync(configPath, `${HEADER}\nhttp:\n  routers: {}\n# an old version\n`);

  const { script, content } = buildTraefikApplyScript(routesNamed('zeta', 'alpha'), configPath, 'http://127.0.0.1:8080');
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  writeCurlStub(stubDir, '200');
  writeSleepStub(stubDir);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}`, BELLHOP_TEST_BAD_ROUTER: NO_BAD_ROUTER };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.equal(result.status, 0, `expected exit 0, got ${result.status}, stderr: ${result.stderr}`);
  assert.equal(readFileSync(configPath, 'utf8'), `${content}\n`, 'the newly rendered file must be kept');
});

test('buildApiCheck, executed: the marker never answers 200 -> exit non-zero, stderr names the timeout and HTTP 404, the previous file is restored', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }
  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-traefik-api-check-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-traefik-api-check-stubs-'));
  const configPath = posix(join(tmpDir, 'bellhop.yml'));
  const originalContent = `${HEADER}\nhttp:\n  routers: {}\n# the previous version\n`;
  writeFileSync(configPath, originalContent);

  const { script } = buildTraefikApplyScript(routesNamed('app'), configPath, 'http://127.0.0.1:8080');
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  writeCurlStub(stubDir, '404');
  writeSleepStub(stubDir);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}`, BELLHOP_TEST_BAD_ROUTER: NO_BAD_ROUTER };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.notEqual(result.status, 0, `expected a non-zero exit, got ${result.status}`);
  const stderr = result.stderr.toString();
  assert.match(stderr, /did not load .* within 30 seconds \(HTTP 404 at http:\/\/127\.0\.0\.1:8080\)/, `stderr was:\n${stderr}`);
  assert.match(stderr, /Traefik API check failed; restored previous configuration/, `stderr was:\n${stderr}`);
  assert.equal(readFileSync(configPath, 'utf8'), originalContent, 'the previous file must be restored byte for byte');
});

test('buildApiCheck, executed: curl cannot reach the API (000) -> stderr says "unreachable", the previous file is restored', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }
  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-traefik-api-check-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-traefik-api-check-stubs-'));
  const configPath = posix(join(tmpDir, 'bellhop.yml'));
  const originalContent = `${HEADER}\nhttp:\n  routers: {}\n# the previous version\n`;
  writeFileSync(configPath, originalContent);

  const { script } = buildTraefikApplyScript(routesNamed('app'), configPath, 'http://127.0.0.1:8080');
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  writeCurlStub(stubDir, '000');
  writeSleepStub(stubDir);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}`, BELLHOP_TEST_BAD_ROUTER: NO_BAD_ROUTER };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.notEqual(result.status, 0, `expected a non-zero exit, got ${result.status}`);
  const stderr = result.stderr.toString();
  assert.match(stderr, /did not load .* within 30 seconds \(unreachable at http:\/\/127\.0\.0\.1:8080\)/, `stderr was:\n${stderr}`);
  assert.equal(readFileSync(configPath, 'utf8'), originalContent, 'the previous file must be restored byte for byte');
});

test('buildApiCheck, executed: the marker loads but one router is disabled -> stderr names that router and includes its error body, the previous file is restored', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }
  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-traefik-api-check-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-traefik-api-check-stubs-'));
  const configPath = posix(join(tmpDir, 'bellhop.yml'));
  const originalContent = `${HEADER}\nhttp:\n  routers: {}\n# the previous version\n`;
  writeFileSync(configPath, originalContent);

  const { script, content } = buildTraefikApplyScript(routesNamed('zeta', 'alpha'), configPath, 'http://127.0.0.1:8080');
  const badRouter = routerNames(content)[1];
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  writeCurlStub(stubDir, '200');
  writeSleepStub(stubDir);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}`, BELLHOP_TEST_BAD_ROUTER: badRouter };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.notEqual(result.status, 0, `expected a non-zero exit, got ${result.status}`);
  const stderr = result.stderr.toString();
  assert.ok(stderr.includes(`Traefik router ${badRouter} is not healthy:`), `expected the router named, stderr was:\n${stderr}`);
  assert.ok(stderr.includes('does not exist'), `expected the fixture's own error text, stderr was:\n${stderr}`);
  assert.match(stderr, /Traefik API check failed; restored previous configuration/, `stderr was:\n${stderr}`);
  assert.equal(readFileSync(configPath, 'utf8'), originalContent, 'the previous file must be restored byte for byte');
});

test('buildApiCheck, executed: no previous file existed and the check fails -> the file is removed, no temp file left behind', (t) => {
  if (!shAvailable()) {
    t.skip('sh not found on PATH -- cannot execute the generated script');
    return;
  }
  const tmpDir = mkdtempSync(join(tmpdir(), 'bellhop-traefik-api-check-'));
  const stubDir = mkdtempSync(join(tmpdir(), 'bellhop-traefik-api-check-stubs-'));
  const configPath = posix(join(tmpDir, 'bellhop.yml'));
  // configPath's file is deliberately never created -- this is a first-ever
  // apply into a directory that already exists (mktemp needs the directory
  // itself), but no prior bellhop.yml.

  const { script } = buildTraefikApplyScript(routesNamed('app'), configPath, 'http://127.0.0.1:8080');
  const scriptPath = posix(join(tmpDir, 'apply.sh'));
  writeFileSync(scriptPath, script);

  writeCurlStub(stubDir, '404');
  writeSleepStub(stubDir);

  const env = { ...process.env, PATH: `${stubDir}${delimiter}${process.env.PATH}`, BELLHOP_TEST_BAD_ROUTER: NO_BAD_ROUTER };
  const result = spawnSync('sh', [scriptPath], { env });

  assert.notEqual(result.status, 0, `expected a non-zero exit, got ${result.status}`);
  assert.ok(!existsSync(configPath), 'the file must not exist -- it never did');
});
